/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PathlessLayoutTouRouteImport } from './routes/_pathlessLayout/tou'
import { Route as PathlessLayoutSelectOrganizationRouteImport } from './routes/_pathlessLayout/select-organization'
import { Route as PathlessLayoutRegisterRouteImport } from './routes/_pathlessLayout/register'
import { Route as PathlessLayoutPrivacyRouteImport } from './routes/_pathlessLayout/privacy'
import { Route as PathlessLayoutLoginRouteImport } from './routes/_pathlessLayout/login'
import { Route as PathlessLayoutInitRouteImport } from './routes/_pathlessLayout/init'
import { Route as AppUsersRouteRouteImport } from './routes/app/users/route'
import { Route as AppQuotasRouteRouteImport } from './routes/app/quotas/route'
import { Route as AppProvidersRouteRouteImport } from './routes/app/providers/route'
import { Route as AppOrgsRouteRouteImport } from './routes/app/orgs/route'
import { Route as AppModelsRouteRouteImport } from './routes/app/models/route'
import { Route as AppHubRouteRouteImport } from './routes/app/hub/route'
import { Route as AppGroupsRouteRouteImport } from './routes/app/groups/route'
import { Route as AppChatRouteRouteImport } from './routes/app/chat/route'
import { Route as AppAccountRouteRouteImport } from './routes/app/account/route'
import { Route as AppUsersIndexRouteImport } from './routes/app/users/index'
import { Route as AppQuotasIndexRouteImport } from './routes/app/quotas/index'
import { Route as AppProvidersIndexRouteImport } from './routes/app/providers/index'
import { Route as AppOrgsIndexRouteImport } from './routes/app/orgs/index'
import { Route as AppModelsIndexRouteImport } from './routes/app/models/index'
import { Route as AppHubIndexRouteImport } from './routes/app/hub/index'
import { Route as AppGroupsIndexRouteImport } from './routes/app/groups/index'
import { Route as AppChatIndexRouteImport } from './routes/app/chat/index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account/index'
import { Route as AppUsersInvitesRouteImport } from './routes/app/users/invites'
import { Route as AppUsersAddRouteImport } from './routes/app/users/add'
import { Route as AppQuotasAddRouteImport } from './routes/app/quotas/add'
import { Route as AppProvidersAddRouteImport } from './routes/app/providers/add'
import { Route as AppOrgsAddRouteImport } from './routes/app/orgs/add'
import { Route as AppModelsAddRouteImport } from './routes/app/models/add'
import { Route as AppHubRepositoriesRouteImport } from './routes/app/hub/repositories'
import { Route as AppHubBehaviourRouteImport } from './routes/app/hub/behaviour'
import { Route as AppChatSetupRouteImport } from './routes/app/chat/setup'
import { Route as AppChatNewRouteImport } from './routes/app/chat/new'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiDocSplatRouteImport } from './routes/api/doc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppUsersUserIdRouteRouteImport } from './routes/app/users/$userId/route'
import { Route as AppQuotasQuotaPoolIdRouteRouteImport } from './routes/app/quotas/$quotaPoolId/route'
import { Route as AppProvidersProviderIdRouteRouteImport } from './routes/app/providers/$providerId/route'
import { Route as AppOrgsOrgIdRouteRouteImport } from './routes/app/orgs/$orgId/route'
import { Route as AppModelsModelIdRouteRouteImport } from './routes/app/models/$modelId/route'
import { Route as AppHubBotsRouteRouteImport } from './routes/app/hub/bots/route'
import { Route as AppHubBlocksRouteRouteImport } from './routes/app/hub/blocks/route'
import { Route as AppHubAssetsRouteRouteImport } from './routes/app/hub/assets/route'
import { Route as AppGroupsGroupIdRouteRouteImport } from './routes/app/groups/$groupId/route'
import { Route as AppQuotasQuotaPoolIdIndexRouteImport } from './routes/app/quotas/$quotaPoolId/index'
import { Route as AppProvidersProviderIdIndexRouteImport } from './routes/app/providers/$providerId/index'
import { Route as AppOrgsOrgIdIndexRouteImport } from './routes/app/orgs/$orgId/index'
import { Route as AppModelsModelIdIndexRouteImport } from './routes/app/models/$modelId/index'
import { Route as AppHubBotsIndexRouteImport } from './routes/app/hub/bots/index'
import { Route as AppHubBlocksIndexRouteImport } from './routes/app/hub/blocks/index'
import { Route as AppHubAssetsIndexRouteImport } from './routes/app/hub/assets/index'
import { Route as AppGroupsGroupIdIndexRouteImport } from './routes/app/groups/$groupId/index'
import { Route as AppChatChatIdIndexRouteImport } from './routes/app/chat/$chatId/index'
import { Route as AppUsersUserIdEditRouteImport } from './routes/app/users/$userId/edit'
import { Route as AppQuotasQuotaPoolIdEditRouteImport } from './routes/app/quotas/$quotaPoolId/edit'
import { Route as AppProvidersProviderIdEditRouteImport } from './routes/app/providers/$providerId/edit'
import { Route as AppOrgsOrgIdEditRouteImport } from './routes/app/orgs/$orgId/edit'
import { Route as AppModelsModelIdEditRouteImport } from './routes/app/models/$modelId/edit'
import { Route as AppHubBotsAddRouteImport } from './routes/app/hub/bots/add'
import { Route as AppHubBlocksAddRouteImport } from './routes/app/hub/blocks/add'
import { Route as AppHubAssetsPlaygroundRouteImport } from './routes/app/hub/assets/playground'
import { Route as AppHubAssetsAddRouteImport } from './routes/app/hub/assets/add'
import { Route as AppHubBotsBotIdRouteRouteImport } from './routes/app/hub/bots/$botId/route'
import { Route as AppHubBlocksBlockIdRouteRouteImport } from './routes/app/hub/blocks/$blockId/route'
import { Route as AppHubAssetsAssetIdRouteRouteImport } from './routes/app/hub/assets/$assetId/route'
import { Route as AppHubBotsBotIdIndexRouteImport } from './routes/app/hub/bots/$botId/index'
import { Route as AppHubBlocksBlockIdIndexRouteImport } from './routes/app/hub/blocks/$blockId/index'
import { Route as AppHubAssetsAssetIdIndexRouteImport } from './routes/app/hub/assets/$assetId/index'
import { Route as AppHubBotsBotIdSetupRouteImport } from './routes/app/hub/bots/$botId/setup'
import { Route as AppHubBlocksBlockIdPointsRouteImport } from './routes/app/hub/blocks/$blockId/points'
import { Route as AppHubBlocksBlockIdEditRouteImport } from './routes/app/hub/blocks/$blockId/edit'
import { Route as AppHubAssetsAssetIdEditRouteImport } from './routes/app/hub/assets/$assetId/edit'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PathlessLayoutTouRoute = PathlessLayoutTouRouteImport.update({
  id: '/tou',
  path: '/tou',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutSelectOrganizationRoute =
  PathlessLayoutSelectOrganizationRouteImport.update({
    id: '/select-organization',
    path: '/select-organization',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutRegisterRoute = PathlessLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutPrivacyRoute = PathlessLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutLoginRoute = PathlessLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutInitRoute = PathlessLayoutInitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const AppUsersRouteRoute = AppUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotasRouteRoute = AppQuotasRouteRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProvidersRouteRoute = AppProvidersRouteRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrgsRouteRoute = AppOrgsRouteRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModelsRouteRoute = AppModelsRouteRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHubRouteRoute = AppHubRouteRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupsRouteRoute = AppGroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRouteRoute = AppChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRouteRoute = AppAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppQuotasIndexRoute = AppQuotasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQuotasRouteRoute,
} as any)
const AppProvidersIndexRoute = AppProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProvidersRouteRoute,
} as any)
const AppOrgsIndexRoute = AppOrgsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgsRouteRoute,
} as any)
const AppModelsIndexRoute = AppModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppModelsRouteRoute,
} as any)
const AppHubIndexRoute = AppHubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGroupsRouteRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppUsersInvitesRoute = AppUsersInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppUsersAddRoute = AppUsersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppQuotasAddRoute = AppQuotasAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppQuotasRouteRoute,
} as any)
const AppProvidersAddRoute = AppProvidersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppProvidersRouteRoute,
} as any)
const AppOrgsAddRoute = AppOrgsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppOrgsRouteRoute,
} as any)
const AppModelsAddRoute = AppModelsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppModelsRouteRoute,
} as any)
const AppHubRepositoriesRoute = AppHubRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppHubBehaviourRoute = AppHubBehaviourRouteImport.update({
  id: '/behaviour',
  path: '/behaviour',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppChatSetupRoute = AppChatSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppChatRouteRoute,
} as any)
const AppChatNewRoute = AppChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppChatRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocSplatRoute = ApiDocSplatRouteImport.update({
  id: '/api/doc/$',
  path: '/api/doc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersUserIdRouteRoute = AppUsersUserIdRouteRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppQuotasQuotaPoolIdRouteRoute =
  AppQuotasQuotaPoolIdRouteRouteImport.update({
    id: '/$quotaPoolId',
    path: '/$quotaPoolId',
    getParentRoute: () => AppQuotasRouteRoute,
  } as any)
const AppProvidersProviderIdRouteRoute =
  AppProvidersProviderIdRouteRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => AppProvidersRouteRoute,
  } as any)
const AppOrgsOrgIdRouteRoute = AppOrgsOrgIdRouteRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AppOrgsRouteRoute,
} as any)
const AppModelsModelIdRouteRoute = AppModelsModelIdRouteRouteImport.update({
  id: '/$modelId',
  path: '/$modelId',
  getParentRoute: () => AppModelsRouteRoute,
} as any)
const AppHubBotsRouteRoute = AppHubBotsRouteRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppHubBlocksRouteRoute = AppHubBlocksRouteRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppHubAssetsRouteRoute = AppHubAssetsRouteRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppGroupsGroupIdRouteRoute = AppGroupsGroupIdRouteRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AppGroupsRouteRoute,
} as any)
const AppQuotasQuotaPoolIdIndexRoute =
  AppQuotasQuotaPoolIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppQuotasQuotaPoolIdRouteRoute,
  } as any)
const AppProvidersProviderIdIndexRoute =
  AppProvidersProviderIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProvidersProviderIdRouteRoute,
  } as any)
const AppOrgsOrgIdIndexRoute = AppOrgsOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgsOrgIdRouteRoute,
} as any)
const AppModelsModelIdIndexRoute = AppModelsModelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppModelsModelIdRouteRoute,
} as any)
const AppHubBotsIndexRoute = AppHubBotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHubBotsRouteRoute,
} as any)
const AppHubBlocksIndexRoute = AppHubBlocksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHubBlocksRouteRoute,
} as any)
const AppHubAssetsIndexRoute = AppHubAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHubAssetsRouteRoute,
} as any)
const AppGroupsGroupIdIndexRoute = AppGroupsGroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGroupsGroupIdRouteRoute,
} as any)
const AppChatChatIdIndexRoute = AppChatChatIdIndexRouteImport.update({
  id: '/$chatId/',
  path: '/$chatId/',
  getParentRoute: () => AppChatRouteRoute,
} as any)
const AppUsersUserIdEditRoute = AppUsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppUsersUserIdRouteRoute,
} as any)
const AppQuotasQuotaPoolIdEditRoute =
  AppQuotasQuotaPoolIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppQuotasQuotaPoolIdRouteRoute,
  } as any)
const AppProvidersProviderIdEditRoute =
  AppProvidersProviderIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppProvidersProviderIdRouteRoute,
  } as any)
const AppOrgsOrgIdEditRoute = AppOrgsOrgIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppOrgsOrgIdRouteRoute,
} as any)
const AppModelsModelIdEditRoute = AppModelsModelIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppModelsModelIdRouteRoute,
} as any)
const AppHubBotsAddRoute = AppHubBotsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppHubBotsRouteRoute,
} as any)
const AppHubBlocksAddRoute = AppHubBlocksAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppHubBlocksRouteRoute,
} as any)
const AppHubAssetsPlaygroundRoute = AppHubAssetsPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppHubAssetsRouteRoute,
} as any)
const AppHubAssetsAddRoute = AppHubAssetsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppHubAssetsRouteRoute,
} as any)
const AppHubBotsBotIdRouteRoute = AppHubBotsBotIdRouteRouteImport.update({
  id: '/$botId',
  path: '/$botId',
  getParentRoute: () => AppHubBotsRouteRoute,
} as any)
const AppHubBlocksBlockIdRouteRoute =
  AppHubBlocksBlockIdRouteRouteImport.update({
    id: '/$blockId',
    path: '/$blockId',
    getParentRoute: () => AppHubBlocksRouteRoute,
  } as any)
const AppHubAssetsAssetIdRouteRoute =
  AppHubAssetsAssetIdRouteRouteImport.update({
    id: '/$assetId',
    path: '/$assetId',
    getParentRoute: () => AppHubAssetsRouteRoute,
  } as any)
const AppHubBotsBotIdIndexRoute = AppHubBotsBotIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHubBotsBotIdRouteRoute,
} as any)
const AppHubBlocksBlockIdIndexRoute =
  AppHubBlocksBlockIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppHubBlocksBlockIdRouteRoute,
  } as any)
const AppHubAssetsAssetIdIndexRoute =
  AppHubAssetsAssetIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppHubAssetsAssetIdRouteRoute,
  } as any)
const AppHubBotsBotIdSetupRoute = AppHubBotsBotIdSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppHubBotsBotIdRouteRoute,
} as any)
const AppHubBlocksBlockIdPointsRoute =
  AppHubBlocksBlockIdPointsRouteImport.update({
    id: '/points',
    path: '/points',
    getParentRoute: () => AppHubBlocksBlockIdRouteRoute,
  } as any)
const AppHubBlocksBlockIdEditRoute = AppHubBlocksBlockIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppHubBlocksBlockIdRouteRoute,
} as any)
const AppHubAssetsAssetIdEditRoute = AppHubAssetsAssetIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppHubAssetsAssetIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/account': typeof AppAccountRouteRouteWithChildren
  '/app/chat': typeof AppChatRouteRouteWithChildren
  '/app/groups': typeof AppGroupsRouteRouteWithChildren
  '/app/hub': typeof AppHubRouteRouteWithChildren
  '/app/models': typeof AppModelsRouteRouteWithChildren
  '/app/orgs': typeof AppOrgsRouteRouteWithChildren
  '/app/providers': typeof AppProvidersRouteRouteWithChildren
  '/app/quotas': typeof AppQuotasRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRouteWithChildren
  '/init': typeof PathlessLayoutInitRoute
  '/login': typeof PathlessLayoutLoginRoute
  '/privacy': typeof PathlessLayoutPrivacyRoute
  '/register': typeof PathlessLayoutRegisterRoute
  '/select-organization': typeof PathlessLayoutSelectOrganizationRoute
  '/tou': typeof PathlessLayoutTouRoute
  '/app/': typeof AppIndexRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdRouteRouteWithChildren
  '/app/hub/assets': typeof AppHubAssetsRouteRouteWithChildren
  '/app/hub/blocks': typeof AppHubBlocksRouteRouteWithChildren
  '/app/hub/bots': typeof AppHubBotsRouteRouteWithChildren
  '/app/models/$modelId': typeof AppModelsModelIdRouteRouteWithChildren
  '/app/orgs/$orgId': typeof AppOrgsOrgIdRouteRouteWithChildren
  '/app/providers/$providerId': typeof AppProvidersProviderIdRouteRouteWithChildren
  '/app/quotas/$quotaPoolId': typeof AppQuotasQuotaPoolIdRouteRouteWithChildren
  '/app/users/$userId': typeof AppUsersUserIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/doc/$': typeof ApiDocSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/chat/new': typeof AppChatNewRoute
  '/app/chat/setup': typeof AppChatSetupRoute
  '/app/hub/behaviour': typeof AppHubBehaviourRoute
  '/app/hub/repositories': typeof AppHubRepositoriesRoute
  '/app/models/add': typeof AppModelsAddRoute
  '/app/orgs/add': typeof AppOrgsAddRoute
  '/app/providers/add': typeof AppProvidersAddRoute
  '/app/quotas/add': typeof AppQuotasAddRoute
  '/app/users/add': typeof AppUsersAddRoute
  '/app/users/invites': typeof AppUsersInvitesRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/groups/': typeof AppGroupsIndexRoute
  '/app/hub/': typeof AppHubIndexRoute
  '/app/models/': typeof AppModelsIndexRoute
  '/app/orgs/': typeof AppOrgsIndexRoute
  '/app/providers/': typeof AppProvidersIndexRoute
  '/app/quotas/': typeof AppQuotasIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/hub/assets/$assetId': typeof AppHubAssetsAssetIdRouteRouteWithChildren
  '/app/hub/blocks/$blockId': typeof AppHubBlocksBlockIdRouteRouteWithChildren
  '/app/hub/bots/$botId': typeof AppHubBotsBotIdRouteRouteWithChildren
  '/app/hub/assets/add': typeof AppHubAssetsAddRoute
  '/app/hub/assets/playground': typeof AppHubAssetsPlaygroundRoute
  '/app/hub/blocks/add': typeof AppHubBlocksAddRoute
  '/app/hub/bots/add': typeof AppHubBotsAddRoute
  '/app/models/$modelId/edit': typeof AppModelsModelIdEditRoute
  '/app/orgs/$orgId/edit': typeof AppOrgsOrgIdEditRoute
  '/app/providers/$providerId/edit': typeof AppProvidersProviderIdEditRoute
  '/app/quotas/$quotaPoolId/edit': typeof AppQuotasQuotaPoolIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/chat/$chatId/': typeof AppChatChatIdIndexRoute
  '/app/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
  '/app/hub/assets/': typeof AppHubAssetsIndexRoute
  '/app/hub/blocks/': typeof AppHubBlocksIndexRoute
  '/app/hub/bots/': typeof AppHubBotsIndexRoute
  '/app/models/$modelId/': typeof AppModelsModelIdIndexRoute
  '/app/orgs/$orgId/': typeof AppOrgsOrgIdIndexRoute
  '/app/providers/$providerId/': typeof AppProvidersProviderIdIndexRoute
  '/app/quotas/$quotaPoolId/': typeof AppQuotasQuotaPoolIdIndexRoute
  '/app/hub/assets/$assetId/edit': typeof AppHubAssetsAssetIdEditRoute
  '/app/hub/blocks/$blockId/edit': typeof AppHubBlocksBlockIdEditRoute
  '/app/hub/blocks/$blockId/points': typeof AppHubBlocksBlockIdPointsRoute
  '/app/hub/bots/$botId/setup': typeof AppHubBotsBotIdSetupRoute
  '/app/hub/assets/$assetId/': typeof AppHubAssetsAssetIdIndexRoute
  '/app/hub/blocks/$blockId/': typeof AppHubBlocksBlockIdIndexRoute
  '/app/hub/bots/$botId/': typeof AppHubBotsBotIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/init': typeof PathlessLayoutInitRoute
  '/login': typeof PathlessLayoutLoginRoute
  '/privacy': typeof PathlessLayoutPrivacyRoute
  '/register': typeof PathlessLayoutRegisterRoute
  '/select-organization': typeof PathlessLayoutSelectOrganizationRoute
  '/tou': typeof PathlessLayoutTouRoute
  '/app': typeof AppIndexRoute
  '/app/users/$userId': typeof AppUsersUserIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/doc/$': typeof ApiDocSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/chat/new': typeof AppChatNewRoute
  '/app/chat/setup': typeof AppChatSetupRoute
  '/app/hub/behaviour': typeof AppHubBehaviourRoute
  '/app/hub/repositories': typeof AppHubRepositoriesRoute
  '/app/models/add': typeof AppModelsAddRoute
  '/app/orgs/add': typeof AppOrgsAddRoute
  '/app/providers/add': typeof AppProvidersAddRoute
  '/app/quotas/add': typeof AppQuotasAddRoute
  '/app/users/add': typeof AppUsersAddRoute
  '/app/users/invites': typeof AppUsersInvitesRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/chat': typeof AppChatIndexRoute
  '/app/groups': typeof AppGroupsIndexRoute
  '/app/hub': typeof AppHubIndexRoute
  '/app/models': typeof AppModelsIndexRoute
  '/app/orgs': typeof AppOrgsIndexRoute
  '/app/providers': typeof AppProvidersIndexRoute
  '/app/quotas': typeof AppQuotasIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/hub/assets/add': typeof AppHubAssetsAddRoute
  '/app/hub/assets/playground': typeof AppHubAssetsPlaygroundRoute
  '/app/hub/blocks/add': typeof AppHubBlocksAddRoute
  '/app/hub/bots/add': typeof AppHubBotsAddRoute
  '/app/models/$modelId/edit': typeof AppModelsModelIdEditRoute
  '/app/orgs/$orgId/edit': typeof AppOrgsOrgIdEditRoute
  '/app/providers/$providerId/edit': typeof AppProvidersProviderIdEditRoute
  '/app/quotas/$quotaPoolId/edit': typeof AppQuotasQuotaPoolIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/chat/$chatId': typeof AppChatChatIdIndexRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdIndexRoute
  '/app/hub/assets': typeof AppHubAssetsIndexRoute
  '/app/hub/blocks': typeof AppHubBlocksIndexRoute
  '/app/hub/bots': typeof AppHubBotsIndexRoute
  '/app/models/$modelId': typeof AppModelsModelIdIndexRoute
  '/app/orgs/$orgId': typeof AppOrgsOrgIdIndexRoute
  '/app/providers/$providerId': typeof AppProvidersProviderIdIndexRoute
  '/app/quotas/$quotaPoolId': typeof AppQuotasQuotaPoolIdIndexRoute
  '/app/hub/assets/$assetId/edit': typeof AppHubAssetsAssetIdEditRoute
  '/app/hub/blocks/$blockId/edit': typeof AppHubBlocksBlockIdEditRoute
  '/app/hub/blocks/$blockId/points': typeof AppHubBlocksBlockIdPointsRoute
  '/app/hub/bots/$botId/setup': typeof AppHubBotsBotIdSetupRoute
  '/app/hub/assets/$assetId': typeof AppHubAssetsAssetIdIndexRoute
  '/app/hub/blocks/$blockId': typeof AppHubBlocksBlockIdIndexRoute
  '/app/hub/bots/$botId': typeof AppHubBotsBotIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/account': typeof AppAccountRouteRouteWithChildren
  '/app/chat': typeof AppChatRouteRouteWithChildren
  '/app/groups': typeof AppGroupsRouteRouteWithChildren
  '/app/hub': typeof AppHubRouteRouteWithChildren
  '/app/models': typeof AppModelsRouteRouteWithChildren
  '/app/orgs': typeof AppOrgsRouteRouteWithChildren
  '/app/providers': typeof AppProvidersRouteRouteWithChildren
  '/app/quotas': typeof AppQuotasRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRouteWithChildren
  '/_pathlessLayout/init': typeof PathlessLayoutInitRoute
  '/_pathlessLayout/login': typeof PathlessLayoutLoginRoute
  '/_pathlessLayout/privacy': typeof PathlessLayoutPrivacyRoute
  '/_pathlessLayout/register': typeof PathlessLayoutRegisterRoute
  '/_pathlessLayout/select-organization': typeof PathlessLayoutSelectOrganizationRoute
  '/_pathlessLayout/tou': typeof PathlessLayoutTouRoute
  '/app/': typeof AppIndexRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdRouteRouteWithChildren
  '/app/hub/assets': typeof AppHubAssetsRouteRouteWithChildren
  '/app/hub/blocks': typeof AppHubBlocksRouteRouteWithChildren
  '/app/hub/bots': typeof AppHubBotsRouteRouteWithChildren
  '/app/models/$modelId': typeof AppModelsModelIdRouteRouteWithChildren
  '/app/orgs/$orgId': typeof AppOrgsOrgIdRouteRouteWithChildren
  '/app/providers/$providerId': typeof AppProvidersProviderIdRouteRouteWithChildren
  '/app/quotas/$quotaPoolId': typeof AppQuotasQuotaPoolIdRouteRouteWithChildren
  '/app/users/$userId': typeof AppUsersUserIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/doc/$': typeof ApiDocSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/chat/new': typeof AppChatNewRoute
  '/app/chat/setup': typeof AppChatSetupRoute
  '/app/hub/behaviour': typeof AppHubBehaviourRoute
  '/app/hub/repositories': typeof AppHubRepositoriesRoute
  '/app/models/add': typeof AppModelsAddRoute
  '/app/orgs/add': typeof AppOrgsAddRoute
  '/app/providers/add': typeof AppProvidersAddRoute
  '/app/quotas/add': typeof AppQuotasAddRoute
  '/app/users/add': typeof AppUsersAddRoute
  '/app/users/invites': typeof AppUsersInvitesRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/groups/': typeof AppGroupsIndexRoute
  '/app/hub/': typeof AppHubIndexRoute
  '/app/models/': typeof AppModelsIndexRoute
  '/app/orgs/': typeof AppOrgsIndexRoute
  '/app/providers/': typeof AppProvidersIndexRoute
  '/app/quotas/': typeof AppQuotasIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/hub/assets/$assetId': typeof AppHubAssetsAssetIdRouteRouteWithChildren
  '/app/hub/blocks/$blockId': typeof AppHubBlocksBlockIdRouteRouteWithChildren
  '/app/hub/bots/$botId': typeof AppHubBotsBotIdRouteRouteWithChildren
  '/app/hub/assets/add': typeof AppHubAssetsAddRoute
  '/app/hub/assets/playground': typeof AppHubAssetsPlaygroundRoute
  '/app/hub/blocks/add': typeof AppHubBlocksAddRoute
  '/app/hub/bots/add': typeof AppHubBotsAddRoute
  '/app/models/$modelId/edit': typeof AppModelsModelIdEditRoute
  '/app/orgs/$orgId/edit': typeof AppOrgsOrgIdEditRoute
  '/app/providers/$providerId/edit': typeof AppProvidersProviderIdEditRoute
  '/app/quotas/$quotaPoolId/edit': typeof AppQuotasQuotaPoolIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/chat/$chatId/': typeof AppChatChatIdIndexRoute
  '/app/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
  '/app/hub/assets/': typeof AppHubAssetsIndexRoute
  '/app/hub/blocks/': typeof AppHubBlocksIndexRoute
  '/app/hub/bots/': typeof AppHubBotsIndexRoute
  '/app/models/$modelId/': typeof AppModelsModelIdIndexRoute
  '/app/orgs/$orgId/': typeof AppOrgsOrgIdIndexRoute
  '/app/providers/$providerId/': typeof AppProvidersProviderIdIndexRoute
  '/app/quotas/$quotaPoolId/': typeof AppQuotasQuotaPoolIdIndexRoute
  '/app/hub/assets/$assetId/edit': typeof AppHubAssetsAssetIdEditRoute
  '/app/hub/blocks/$blockId/edit': typeof AppHubBlocksBlockIdEditRoute
  '/app/hub/blocks/$blockId/points': typeof AppHubBlocksBlockIdPointsRoute
  '/app/hub/bots/$botId/setup': typeof AppHubBotsBotIdSetupRoute
  '/app/hub/assets/$assetId/': typeof AppHubAssetsAssetIdIndexRoute
  '/app/hub/blocks/$blockId/': typeof AppHubBlocksBlockIdIndexRoute
  '/app/hub/bots/$botId/': typeof AppHubBotsBotIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/account'
    | '/app/chat'
    | '/app/groups'
    | '/app/hub'
    | '/app/models'
    | '/app/orgs'
    | '/app/providers'
    | '/app/quotas'
    | '/app/users'
    | '/init'
    | '/login'
    | '/privacy'
    | '/register'
    | '/select-organization'
    | '/tou'
    | '/app/'
    | '/app/groups/$groupId'
    | '/app/hub/assets'
    | '/app/hub/blocks'
    | '/app/hub/bots'
    | '/app/models/$modelId'
    | '/app/orgs/$orgId'
    | '/app/providers/$providerId'
    | '/app/quotas/$quotaPoolId'
    | '/app/users/$userId'
    | '/api/auth/$'
    | '/api/doc/$'
    | '/api/rpc/$'
    | '/app/chat/new'
    | '/app/chat/setup'
    | '/app/hub/behaviour'
    | '/app/hub/repositories'
    | '/app/models/add'
    | '/app/orgs/add'
    | '/app/providers/add'
    | '/app/quotas/add'
    | '/app/users/add'
    | '/app/users/invites'
    | '/app/account/'
    | '/app/chat/'
    | '/app/groups/'
    | '/app/hub/'
    | '/app/models/'
    | '/app/orgs/'
    | '/app/providers/'
    | '/app/quotas/'
    | '/app/users/'
    | '/app/hub/assets/$assetId'
    | '/app/hub/blocks/$blockId'
    | '/app/hub/bots/$botId'
    | '/app/hub/assets/add'
    | '/app/hub/assets/playground'
    | '/app/hub/blocks/add'
    | '/app/hub/bots/add'
    | '/app/models/$modelId/edit'
    | '/app/orgs/$orgId/edit'
    | '/app/providers/$providerId/edit'
    | '/app/quotas/$quotaPoolId/edit'
    | '/app/users/$userId/edit'
    | '/app/chat/$chatId/'
    | '/app/groups/$groupId/'
    | '/app/hub/assets/'
    | '/app/hub/blocks/'
    | '/app/hub/bots/'
    | '/app/models/$modelId/'
    | '/app/orgs/$orgId/'
    | '/app/providers/$providerId/'
    | '/app/quotas/$quotaPoolId/'
    | '/app/hub/assets/$assetId/edit'
    | '/app/hub/blocks/$blockId/edit'
    | '/app/hub/blocks/$blockId/points'
    | '/app/hub/bots/$botId/setup'
    | '/app/hub/assets/$assetId/'
    | '/app/hub/blocks/$blockId/'
    | '/app/hub/bots/$botId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/init'
    | '/login'
    | '/privacy'
    | '/register'
    | '/select-organization'
    | '/tou'
    | '/app'
    | '/app/users/$userId'
    | '/api/auth/$'
    | '/api/doc/$'
    | '/api/rpc/$'
    | '/app/chat/new'
    | '/app/chat/setup'
    | '/app/hub/behaviour'
    | '/app/hub/repositories'
    | '/app/models/add'
    | '/app/orgs/add'
    | '/app/providers/add'
    | '/app/quotas/add'
    | '/app/users/add'
    | '/app/users/invites'
    | '/app/account'
    | '/app/chat'
    | '/app/groups'
    | '/app/hub'
    | '/app/models'
    | '/app/orgs'
    | '/app/providers'
    | '/app/quotas'
    | '/app/users'
    | '/app/hub/assets/add'
    | '/app/hub/assets/playground'
    | '/app/hub/blocks/add'
    | '/app/hub/bots/add'
    | '/app/models/$modelId/edit'
    | '/app/orgs/$orgId/edit'
    | '/app/providers/$providerId/edit'
    | '/app/quotas/$quotaPoolId/edit'
    | '/app/users/$userId/edit'
    | '/app/chat/$chatId'
    | '/app/groups/$groupId'
    | '/app/hub/assets'
    | '/app/hub/blocks'
    | '/app/hub/bots'
    | '/app/models/$modelId'
    | '/app/orgs/$orgId'
    | '/app/providers/$providerId'
    | '/app/quotas/$quotaPoolId'
    | '/app/hub/assets/$assetId/edit'
    | '/app/hub/blocks/$blockId/edit'
    | '/app/hub/blocks/$blockId/points'
    | '/app/hub/bots/$botId/setup'
    | '/app/hub/assets/$assetId'
    | '/app/hub/blocks/$blockId'
    | '/app/hub/bots/$botId'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/app'
    | '/app/account'
    | '/app/chat'
    | '/app/groups'
    | '/app/hub'
    | '/app/models'
    | '/app/orgs'
    | '/app/providers'
    | '/app/quotas'
    | '/app/users'
    | '/_pathlessLayout/init'
    | '/_pathlessLayout/login'
    | '/_pathlessLayout/privacy'
    | '/_pathlessLayout/register'
    | '/_pathlessLayout/select-organization'
    | '/_pathlessLayout/tou'
    | '/app/'
    | '/app/groups/$groupId'
    | '/app/hub/assets'
    | '/app/hub/blocks'
    | '/app/hub/bots'
    | '/app/models/$modelId'
    | '/app/orgs/$orgId'
    | '/app/providers/$providerId'
    | '/app/quotas/$quotaPoolId'
    | '/app/users/$userId'
    | '/api/auth/$'
    | '/api/doc/$'
    | '/api/rpc/$'
    | '/app/chat/new'
    | '/app/chat/setup'
    | '/app/hub/behaviour'
    | '/app/hub/repositories'
    | '/app/models/add'
    | '/app/orgs/add'
    | '/app/providers/add'
    | '/app/quotas/add'
    | '/app/users/add'
    | '/app/users/invites'
    | '/app/account/'
    | '/app/chat/'
    | '/app/groups/'
    | '/app/hub/'
    | '/app/models/'
    | '/app/orgs/'
    | '/app/providers/'
    | '/app/quotas/'
    | '/app/users/'
    | '/app/hub/assets/$assetId'
    | '/app/hub/blocks/$blockId'
    | '/app/hub/bots/$botId'
    | '/app/hub/assets/add'
    | '/app/hub/assets/playground'
    | '/app/hub/blocks/add'
    | '/app/hub/bots/add'
    | '/app/models/$modelId/edit'
    | '/app/orgs/$orgId/edit'
    | '/app/providers/$providerId/edit'
    | '/app/quotas/$quotaPoolId/edit'
    | '/app/users/$userId/edit'
    | '/app/chat/$chatId/'
    | '/app/groups/$groupId/'
    | '/app/hub/assets/'
    | '/app/hub/blocks/'
    | '/app/hub/bots/'
    | '/app/models/$modelId/'
    | '/app/orgs/$orgId/'
    | '/app/providers/$providerId/'
    | '/app/quotas/$quotaPoolId/'
    | '/app/hub/assets/$assetId/edit'
    | '/app/hub/blocks/$blockId/edit'
    | '/app/hub/blocks/$blockId/points'
    | '/app/hub/bots/$botId/setup'
    | '/app/hub/assets/$assetId/'
    | '/app/hub/blocks/$blockId/'
    | '/app/hub/bots/$botId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocSplatRoute: typeof ApiDocSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_pathlessLayout/tou': {
      id: '/_pathlessLayout/tou'
      path: '/tou'
      fullPath: '/tou'
      preLoaderRoute: typeof PathlessLayoutTouRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/select-organization': {
      id: '/_pathlessLayout/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof PathlessLayoutSelectOrganizationRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/register': {
      id: '/_pathlessLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PathlessLayoutRegisterRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/privacy': {
      id: '/_pathlessLayout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PathlessLayoutPrivacyRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/login': {
      id: '/_pathlessLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PathlessLayoutLoginRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/init': {
      id: '/_pathlessLayout/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof PathlessLayoutInitRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/quotas': {
      id: '/app/quotas'
      path: '/quotas'
      fullPath: '/app/quotas'
      preLoaderRoute: typeof AppQuotasRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/providers': {
      id: '/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AppProvidersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orgs': {
      id: '/app/orgs'
      path: '/orgs'
      fullPath: '/app/orgs'
      preLoaderRoute: typeof AppOrgsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/models': {
      id: '/app/models'
      path: '/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppModelsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/hub': {
      id: '/app/hub'
      path: '/hub'
      fullPath: '/app/hub'
      preLoaderRoute: typeof AppHubRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/groups': {
      id: '/app/groups'
      path: '/groups'
      fullPath: '/app/groups'
      preLoaderRoute: typeof AppGroupsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/quotas/': {
      id: '/app/quotas/'
      path: '/'
      fullPath: '/app/quotas/'
      preLoaderRoute: typeof AppQuotasIndexRouteImport
      parentRoute: typeof AppQuotasRouteRoute
    }
    '/app/providers/': {
      id: '/app/providers/'
      path: '/'
      fullPath: '/app/providers/'
      preLoaderRoute: typeof AppProvidersIndexRouteImport
      parentRoute: typeof AppProvidersRouteRoute
    }
    '/app/orgs/': {
      id: '/app/orgs/'
      path: '/'
      fullPath: '/app/orgs/'
      preLoaderRoute: typeof AppOrgsIndexRouteImport
      parentRoute: typeof AppOrgsRouteRoute
    }
    '/app/models/': {
      id: '/app/models/'
      path: '/'
      fullPath: '/app/models/'
      preLoaderRoute: typeof AppModelsIndexRouteImport
      parentRoute: typeof AppModelsRouteRoute
    }
    '/app/hub/': {
      id: '/app/hub/'
      path: '/'
      fullPath: '/app/hub/'
      preLoaderRoute: typeof AppHubIndexRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/app/groups/': {
      id: '/app/groups/'
      path: '/'
      fullPath: '/app/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppGroupsRouteRoute
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/app/users/invites': {
      id: '/app/users/invites'
      path: '/invites'
      fullPath: '/app/users/invites'
      preLoaderRoute: typeof AppUsersInvitesRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/users/add': {
      id: '/app/users/add'
      path: '/add'
      fullPath: '/app/users/add'
      preLoaderRoute: typeof AppUsersAddRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/quotas/add': {
      id: '/app/quotas/add'
      path: '/add'
      fullPath: '/app/quotas/add'
      preLoaderRoute: typeof AppQuotasAddRouteImport
      parentRoute: typeof AppQuotasRouteRoute
    }
    '/app/providers/add': {
      id: '/app/providers/add'
      path: '/add'
      fullPath: '/app/providers/add'
      preLoaderRoute: typeof AppProvidersAddRouteImport
      parentRoute: typeof AppProvidersRouteRoute
    }
    '/app/orgs/add': {
      id: '/app/orgs/add'
      path: '/add'
      fullPath: '/app/orgs/add'
      preLoaderRoute: typeof AppOrgsAddRouteImport
      parentRoute: typeof AppOrgsRouteRoute
    }
    '/app/models/add': {
      id: '/app/models/add'
      path: '/add'
      fullPath: '/app/models/add'
      preLoaderRoute: typeof AppModelsAddRouteImport
      parentRoute: typeof AppModelsRouteRoute
    }
    '/app/hub/repositories': {
      id: '/app/hub/repositories'
      path: '/repositories'
      fullPath: '/app/hub/repositories'
      preLoaderRoute: typeof AppHubRepositoriesRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/app/hub/behaviour': {
      id: '/app/hub/behaviour'
      path: '/behaviour'
      fullPath: '/app/hub/behaviour'
      preLoaderRoute: typeof AppHubBehaviourRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/app/chat/setup': {
      id: '/app/chat/setup'
      path: '/setup'
      fullPath: '/app/chat/setup'
      preLoaderRoute: typeof AppChatSetupRouteImport
      parentRoute: typeof AppChatRouteRoute
    }
    '/app/chat/new': {
      id: '/app/chat/new'
      path: '/new'
      fullPath: '/app/chat/new'
      preLoaderRoute: typeof AppChatNewRouteImport
      parentRoute: typeof AppChatRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc/$': {
      id: '/api/doc/$'
      path: '/api/doc/$'
      fullPath: '/api/doc/$'
      preLoaderRoute: typeof ApiDocSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users/$userId': {
      id: '/app/users/$userId'
      path: '/$userId'
      fullPath: '/app/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/quotas/$quotaPoolId': {
      id: '/app/quotas/$quotaPoolId'
      path: '/$quotaPoolId'
      fullPath: '/app/quotas/$quotaPoolId'
      preLoaderRoute: typeof AppQuotasQuotaPoolIdRouteRouteImport
      parentRoute: typeof AppQuotasRouteRoute
    }
    '/app/providers/$providerId': {
      id: '/app/providers/$providerId'
      path: '/$providerId'
      fullPath: '/app/providers/$providerId'
      preLoaderRoute: typeof AppProvidersProviderIdRouteRouteImport
      parentRoute: typeof AppProvidersRouteRoute
    }
    '/app/orgs/$orgId': {
      id: '/app/orgs/$orgId'
      path: '/$orgId'
      fullPath: '/app/orgs/$orgId'
      preLoaderRoute: typeof AppOrgsOrgIdRouteRouteImport
      parentRoute: typeof AppOrgsRouteRoute
    }
    '/app/models/$modelId': {
      id: '/app/models/$modelId'
      path: '/$modelId'
      fullPath: '/app/models/$modelId'
      preLoaderRoute: typeof AppModelsModelIdRouteRouteImport
      parentRoute: typeof AppModelsRouteRoute
    }
    '/app/hub/bots': {
      id: '/app/hub/bots'
      path: '/bots'
      fullPath: '/app/hub/bots'
      preLoaderRoute: typeof AppHubBotsRouteRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/app/hub/blocks': {
      id: '/app/hub/blocks'
      path: '/blocks'
      fullPath: '/app/hub/blocks'
      preLoaderRoute: typeof AppHubBlocksRouteRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/app/hub/assets': {
      id: '/app/hub/assets'
      path: '/assets'
      fullPath: '/app/hub/assets'
      preLoaderRoute: typeof AppHubAssetsRouteRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/app/groups/$groupId': {
      id: '/app/groups/$groupId'
      path: '/$groupId'
      fullPath: '/app/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteRouteImport
      parentRoute: typeof AppGroupsRouteRoute
    }
    '/app/quotas/$quotaPoolId/': {
      id: '/app/quotas/$quotaPoolId/'
      path: '/'
      fullPath: '/app/quotas/$quotaPoolId/'
      preLoaderRoute: typeof AppQuotasQuotaPoolIdIndexRouteImport
      parentRoute: typeof AppQuotasQuotaPoolIdRouteRoute
    }
    '/app/providers/$providerId/': {
      id: '/app/providers/$providerId/'
      path: '/'
      fullPath: '/app/providers/$providerId/'
      preLoaderRoute: typeof AppProvidersProviderIdIndexRouteImport
      parentRoute: typeof AppProvidersProviderIdRouteRoute
    }
    '/app/orgs/$orgId/': {
      id: '/app/orgs/$orgId/'
      path: '/'
      fullPath: '/app/orgs/$orgId/'
      preLoaderRoute: typeof AppOrgsOrgIdIndexRouteImport
      parentRoute: typeof AppOrgsOrgIdRouteRoute
    }
    '/app/models/$modelId/': {
      id: '/app/models/$modelId/'
      path: '/'
      fullPath: '/app/models/$modelId/'
      preLoaderRoute: typeof AppModelsModelIdIndexRouteImport
      parentRoute: typeof AppModelsModelIdRouteRoute
    }
    '/app/hub/bots/': {
      id: '/app/hub/bots/'
      path: '/'
      fullPath: '/app/hub/bots/'
      preLoaderRoute: typeof AppHubBotsIndexRouteImport
      parentRoute: typeof AppHubBotsRouteRoute
    }
    '/app/hub/blocks/': {
      id: '/app/hub/blocks/'
      path: '/'
      fullPath: '/app/hub/blocks/'
      preLoaderRoute: typeof AppHubBlocksIndexRouteImport
      parentRoute: typeof AppHubBlocksRouteRoute
    }
    '/app/hub/assets/': {
      id: '/app/hub/assets/'
      path: '/'
      fullPath: '/app/hub/assets/'
      preLoaderRoute: typeof AppHubAssetsIndexRouteImport
      parentRoute: typeof AppHubAssetsRouteRoute
    }
    '/app/groups/$groupId/': {
      id: '/app/groups/$groupId/'
      path: '/'
      fullPath: '/app/groups/$groupId/'
      preLoaderRoute: typeof AppGroupsGroupIdIndexRouteImport
      parentRoute: typeof AppGroupsGroupIdRouteRoute
    }
    '/app/chat/$chatId/': {
      id: '/app/chat/$chatId/'
      path: '/$chatId'
      fullPath: '/app/chat/$chatId/'
      preLoaderRoute: typeof AppChatChatIdIndexRouteImport
      parentRoute: typeof AppChatRouteRoute
    }
    '/app/users/$userId/edit': {
      id: '/app/users/$userId/edit'
      path: '/edit'
      fullPath: '/app/users/$userId/edit'
      preLoaderRoute: typeof AppUsersUserIdEditRouteImport
      parentRoute: typeof AppUsersUserIdRouteRoute
    }
    '/app/quotas/$quotaPoolId/edit': {
      id: '/app/quotas/$quotaPoolId/edit'
      path: '/edit'
      fullPath: '/app/quotas/$quotaPoolId/edit'
      preLoaderRoute: typeof AppQuotasQuotaPoolIdEditRouteImport
      parentRoute: typeof AppQuotasQuotaPoolIdRouteRoute
    }
    '/app/providers/$providerId/edit': {
      id: '/app/providers/$providerId/edit'
      path: '/edit'
      fullPath: '/app/providers/$providerId/edit'
      preLoaderRoute: typeof AppProvidersProviderIdEditRouteImport
      parentRoute: typeof AppProvidersProviderIdRouteRoute
    }
    '/app/orgs/$orgId/edit': {
      id: '/app/orgs/$orgId/edit'
      path: '/edit'
      fullPath: '/app/orgs/$orgId/edit'
      preLoaderRoute: typeof AppOrgsOrgIdEditRouteImport
      parentRoute: typeof AppOrgsOrgIdRouteRoute
    }
    '/app/models/$modelId/edit': {
      id: '/app/models/$modelId/edit'
      path: '/edit'
      fullPath: '/app/models/$modelId/edit'
      preLoaderRoute: typeof AppModelsModelIdEditRouteImport
      parentRoute: typeof AppModelsModelIdRouteRoute
    }
    '/app/hub/bots/add': {
      id: '/app/hub/bots/add'
      path: '/add'
      fullPath: '/app/hub/bots/add'
      preLoaderRoute: typeof AppHubBotsAddRouteImport
      parentRoute: typeof AppHubBotsRouteRoute
    }
    '/app/hub/blocks/add': {
      id: '/app/hub/blocks/add'
      path: '/add'
      fullPath: '/app/hub/blocks/add'
      preLoaderRoute: typeof AppHubBlocksAddRouteImport
      parentRoute: typeof AppHubBlocksRouteRoute
    }
    '/app/hub/assets/playground': {
      id: '/app/hub/assets/playground'
      path: '/playground'
      fullPath: '/app/hub/assets/playground'
      preLoaderRoute: typeof AppHubAssetsPlaygroundRouteImport
      parentRoute: typeof AppHubAssetsRouteRoute
    }
    '/app/hub/assets/add': {
      id: '/app/hub/assets/add'
      path: '/add'
      fullPath: '/app/hub/assets/add'
      preLoaderRoute: typeof AppHubAssetsAddRouteImport
      parentRoute: typeof AppHubAssetsRouteRoute
    }
    '/app/hub/bots/$botId': {
      id: '/app/hub/bots/$botId'
      path: '/$botId'
      fullPath: '/app/hub/bots/$botId'
      preLoaderRoute: typeof AppHubBotsBotIdRouteRouteImport
      parentRoute: typeof AppHubBotsRouteRoute
    }
    '/app/hub/blocks/$blockId': {
      id: '/app/hub/blocks/$blockId'
      path: '/$blockId'
      fullPath: '/app/hub/blocks/$blockId'
      preLoaderRoute: typeof AppHubBlocksBlockIdRouteRouteImport
      parentRoute: typeof AppHubBlocksRouteRoute
    }
    '/app/hub/assets/$assetId': {
      id: '/app/hub/assets/$assetId'
      path: '/$assetId'
      fullPath: '/app/hub/assets/$assetId'
      preLoaderRoute: typeof AppHubAssetsAssetIdRouteRouteImport
      parentRoute: typeof AppHubAssetsRouteRoute
    }
    '/app/hub/bots/$botId/': {
      id: '/app/hub/bots/$botId/'
      path: '/'
      fullPath: '/app/hub/bots/$botId/'
      preLoaderRoute: typeof AppHubBotsBotIdIndexRouteImport
      parentRoute: typeof AppHubBotsBotIdRouteRoute
    }
    '/app/hub/blocks/$blockId/': {
      id: '/app/hub/blocks/$blockId/'
      path: '/'
      fullPath: '/app/hub/blocks/$blockId/'
      preLoaderRoute: typeof AppHubBlocksBlockIdIndexRouteImport
      parentRoute: typeof AppHubBlocksBlockIdRouteRoute
    }
    '/app/hub/assets/$assetId/': {
      id: '/app/hub/assets/$assetId/'
      path: '/'
      fullPath: '/app/hub/assets/$assetId/'
      preLoaderRoute: typeof AppHubAssetsAssetIdIndexRouteImport
      parentRoute: typeof AppHubAssetsAssetIdRouteRoute
    }
    '/app/hub/bots/$botId/setup': {
      id: '/app/hub/bots/$botId/setup'
      path: '/setup'
      fullPath: '/app/hub/bots/$botId/setup'
      preLoaderRoute: typeof AppHubBotsBotIdSetupRouteImport
      parentRoute: typeof AppHubBotsBotIdRouteRoute
    }
    '/app/hub/blocks/$blockId/points': {
      id: '/app/hub/blocks/$blockId/points'
      path: '/points'
      fullPath: '/app/hub/blocks/$blockId/points'
      preLoaderRoute: typeof AppHubBlocksBlockIdPointsRouteImport
      parentRoute: typeof AppHubBlocksBlockIdRouteRoute
    }
    '/app/hub/blocks/$blockId/edit': {
      id: '/app/hub/blocks/$blockId/edit'
      path: '/edit'
      fullPath: '/app/hub/blocks/$blockId/edit'
      preLoaderRoute: typeof AppHubBlocksBlockIdEditRouteImport
      parentRoute: typeof AppHubBlocksBlockIdRouteRoute
    }
    '/app/hub/assets/$assetId/edit': {
      id: '/app/hub/assets/$assetId/edit'
      path: '/edit'
      fullPath: '/app/hub/assets/$assetId/edit'
      preLoaderRoute: typeof AppHubAssetsAssetIdEditRouteImport
      parentRoute: typeof AppHubAssetsAssetIdRouteRoute
    }
  }
}

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutInitRoute: typeof PathlessLayoutInitRoute
  PathlessLayoutLoginRoute: typeof PathlessLayoutLoginRoute
  PathlessLayoutPrivacyRoute: typeof PathlessLayoutPrivacyRoute
  PathlessLayoutRegisterRoute: typeof PathlessLayoutRegisterRoute
  PathlessLayoutSelectOrganizationRoute: typeof PathlessLayoutSelectOrganizationRoute
  PathlessLayoutTouRoute: typeof PathlessLayoutTouRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutInitRoute: PathlessLayoutInitRoute,
  PathlessLayoutLoginRoute: PathlessLayoutLoginRoute,
  PathlessLayoutPrivacyRoute: PathlessLayoutPrivacyRoute,
  PathlessLayoutRegisterRoute: PathlessLayoutRegisterRoute,
  PathlessLayoutSelectOrganizationRoute: PathlessLayoutSelectOrganizationRoute,
  PathlessLayoutTouRoute: PathlessLayoutTouRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

interface AppAccountRouteRouteChildren {
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteRouteChildren: AppAccountRouteRouteChildren = {
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteRouteWithChildren = AppAccountRouteRoute._addFileChildren(
  AppAccountRouteRouteChildren,
)

interface AppChatRouteRouteChildren {
  AppChatNewRoute: typeof AppChatNewRoute
  AppChatSetupRoute: typeof AppChatSetupRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppChatChatIdIndexRoute: typeof AppChatChatIdIndexRoute
}

const AppChatRouteRouteChildren: AppChatRouteRouteChildren = {
  AppChatNewRoute: AppChatNewRoute,
  AppChatSetupRoute: AppChatSetupRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppChatChatIdIndexRoute: AppChatChatIdIndexRoute,
}

const AppChatRouteRouteWithChildren = AppChatRouteRoute._addFileChildren(
  AppChatRouteRouteChildren,
)

interface AppGroupsGroupIdRouteRouteChildren {
  AppGroupsGroupIdIndexRoute: typeof AppGroupsGroupIdIndexRoute
}

const AppGroupsGroupIdRouteRouteChildren: AppGroupsGroupIdRouteRouteChildren = {
  AppGroupsGroupIdIndexRoute: AppGroupsGroupIdIndexRoute,
}

const AppGroupsGroupIdRouteRouteWithChildren =
  AppGroupsGroupIdRouteRoute._addFileChildren(
    AppGroupsGroupIdRouteRouteChildren,
  )

interface AppGroupsRouteRouteChildren {
  AppGroupsGroupIdRouteRoute: typeof AppGroupsGroupIdRouteRouteWithChildren
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
}

const AppGroupsRouteRouteChildren: AppGroupsRouteRouteChildren = {
  AppGroupsGroupIdRouteRoute: AppGroupsGroupIdRouteRouteWithChildren,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
}

const AppGroupsRouteRouteWithChildren = AppGroupsRouteRoute._addFileChildren(
  AppGroupsRouteRouteChildren,
)

interface AppHubAssetsAssetIdRouteRouteChildren {
  AppHubAssetsAssetIdEditRoute: typeof AppHubAssetsAssetIdEditRoute
  AppHubAssetsAssetIdIndexRoute: typeof AppHubAssetsAssetIdIndexRoute
}

const AppHubAssetsAssetIdRouteRouteChildren: AppHubAssetsAssetIdRouteRouteChildren =
  {
    AppHubAssetsAssetIdEditRoute: AppHubAssetsAssetIdEditRoute,
    AppHubAssetsAssetIdIndexRoute: AppHubAssetsAssetIdIndexRoute,
  }

const AppHubAssetsAssetIdRouteRouteWithChildren =
  AppHubAssetsAssetIdRouteRoute._addFileChildren(
    AppHubAssetsAssetIdRouteRouteChildren,
  )

interface AppHubAssetsRouteRouteChildren {
  AppHubAssetsAssetIdRouteRoute: typeof AppHubAssetsAssetIdRouteRouteWithChildren
  AppHubAssetsAddRoute: typeof AppHubAssetsAddRoute
  AppHubAssetsPlaygroundRoute: typeof AppHubAssetsPlaygroundRoute
  AppHubAssetsIndexRoute: typeof AppHubAssetsIndexRoute
}

const AppHubAssetsRouteRouteChildren: AppHubAssetsRouteRouteChildren = {
  AppHubAssetsAssetIdRouteRoute: AppHubAssetsAssetIdRouteRouteWithChildren,
  AppHubAssetsAddRoute: AppHubAssetsAddRoute,
  AppHubAssetsPlaygroundRoute: AppHubAssetsPlaygroundRoute,
  AppHubAssetsIndexRoute: AppHubAssetsIndexRoute,
}

const AppHubAssetsRouteRouteWithChildren =
  AppHubAssetsRouteRoute._addFileChildren(AppHubAssetsRouteRouteChildren)

interface AppHubBlocksBlockIdRouteRouteChildren {
  AppHubBlocksBlockIdEditRoute: typeof AppHubBlocksBlockIdEditRoute
  AppHubBlocksBlockIdPointsRoute: typeof AppHubBlocksBlockIdPointsRoute
  AppHubBlocksBlockIdIndexRoute: typeof AppHubBlocksBlockIdIndexRoute
}

const AppHubBlocksBlockIdRouteRouteChildren: AppHubBlocksBlockIdRouteRouteChildren =
  {
    AppHubBlocksBlockIdEditRoute: AppHubBlocksBlockIdEditRoute,
    AppHubBlocksBlockIdPointsRoute: AppHubBlocksBlockIdPointsRoute,
    AppHubBlocksBlockIdIndexRoute: AppHubBlocksBlockIdIndexRoute,
  }

const AppHubBlocksBlockIdRouteRouteWithChildren =
  AppHubBlocksBlockIdRouteRoute._addFileChildren(
    AppHubBlocksBlockIdRouteRouteChildren,
  )

interface AppHubBlocksRouteRouteChildren {
  AppHubBlocksBlockIdRouteRoute: typeof AppHubBlocksBlockIdRouteRouteWithChildren
  AppHubBlocksAddRoute: typeof AppHubBlocksAddRoute
  AppHubBlocksIndexRoute: typeof AppHubBlocksIndexRoute
}

const AppHubBlocksRouteRouteChildren: AppHubBlocksRouteRouteChildren = {
  AppHubBlocksBlockIdRouteRoute: AppHubBlocksBlockIdRouteRouteWithChildren,
  AppHubBlocksAddRoute: AppHubBlocksAddRoute,
  AppHubBlocksIndexRoute: AppHubBlocksIndexRoute,
}

const AppHubBlocksRouteRouteWithChildren =
  AppHubBlocksRouteRoute._addFileChildren(AppHubBlocksRouteRouteChildren)

interface AppHubBotsBotIdRouteRouteChildren {
  AppHubBotsBotIdSetupRoute: typeof AppHubBotsBotIdSetupRoute
  AppHubBotsBotIdIndexRoute: typeof AppHubBotsBotIdIndexRoute
}

const AppHubBotsBotIdRouteRouteChildren: AppHubBotsBotIdRouteRouteChildren = {
  AppHubBotsBotIdSetupRoute: AppHubBotsBotIdSetupRoute,
  AppHubBotsBotIdIndexRoute: AppHubBotsBotIdIndexRoute,
}

const AppHubBotsBotIdRouteRouteWithChildren =
  AppHubBotsBotIdRouteRoute._addFileChildren(AppHubBotsBotIdRouteRouteChildren)

interface AppHubBotsRouteRouteChildren {
  AppHubBotsBotIdRouteRoute: typeof AppHubBotsBotIdRouteRouteWithChildren
  AppHubBotsAddRoute: typeof AppHubBotsAddRoute
  AppHubBotsIndexRoute: typeof AppHubBotsIndexRoute
}

const AppHubBotsRouteRouteChildren: AppHubBotsRouteRouteChildren = {
  AppHubBotsBotIdRouteRoute: AppHubBotsBotIdRouteRouteWithChildren,
  AppHubBotsAddRoute: AppHubBotsAddRoute,
  AppHubBotsIndexRoute: AppHubBotsIndexRoute,
}

const AppHubBotsRouteRouteWithChildren = AppHubBotsRouteRoute._addFileChildren(
  AppHubBotsRouteRouteChildren,
)

interface AppHubRouteRouteChildren {
  AppHubAssetsRouteRoute: typeof AppHubAssetsRouteRouteWithChildren
  AppHubBlocksRouteRoute: typeof AppHubBlocksRouteRouteWithChildren
  AppHubBotsRouteRoute: typeof AppHubBotsRouteRouteWithChildren
  AppHubBehaviourRoute: typeof AppHubBehaviourRoute
  AppHubRepositoriesRoute: typeof AppHubRepositoriesRoute
  AppHubIndexRoute: typeof AppHubIndexRoute
}

const AppHubRouteRouteChildren: AppHubRouteRouteChildren = {
  AppHubAssetsRouteRoute: AppHubAssetsRouteRouteWithChildren,
  AppHubBlocksRouteRoute: AppHubBlocksRouteRouteWithChildren,
  AppHubBotsRouteRoute: AppHubBotsRouteRouteWithChildren,
  AppHubBehaviourRoute: AppHubBehaviourRoute,
  AppHubRepositoriesRoute: AppHubRepositoriesRoute,
  AppHubIndexRoute: AppHubIndexRoute,
}

const AppHubRouteRouteWithChildren = AppHubRouteRoute._addFileChildren(
  AppHubRouteRouteChildren,
)

interface AppModelsModelIdRouteRouteChildren {
  AppModelsModelIdEditRoute: typeof AppModelsModelIdEditRoute
  AppModelsModelIdIndexRoute: typeof AppModelsModelIdIndexRoute
}

const AppModelsModelIdRouteRouteChildren: AppModelsModelIdRouteRouteChildren = {
  AppModelsModelIdEditRoute: AppModelsModelIdEditRoute,
  AppModelsModelIdIndexRoute: AppModelsModelIdIndexRoute,
}

const AppModelsModelIdRouteRouteWithChildren =
  AppModelsModelIdRouteRoute._addFileChildren(
    AppModelsModelIdRouteRouteChildren,
  )

interface AppModelsRouteRouteChildren {
  AppModelsModelIdRouteRoute: typeof AppModelsModelIdRouteRouteWithChildren
  AppModelsAddRoute: typeof AppModelsAddRoute
  AppModelsIndexRoute: typeof AppModelsIndexRoute
}

const AppModelsRouteRouteChildren: AppModelsRouteRouteChildren = {
  AppModelsModelIdRouteRoute: AppModelsModelIdRouteRouteWithChildren,
  AppModelsAddRoute: AppModelsAddRoute,
  AppModelsIndexRoute: AppModelsIndexRoute,
}

const AppModelsRouteRouteWithChildren = AppModelsRouteRoute._addFileChildren(
  AppModelsRouteRouteChildren,
)

interface AppOrgsOrgIdRouteRouteChildren {
  AppOrgsOrgIdEditRoute: typeof AppOrgsOrgIdEditRoute
  AppOrgsOrgIdIndexRoute: typeof AppOrgsOrgIdIndexRoute
}

const AppOrgsOrgIdRouteRouteChildren: AppOrgsOrgIdRouteRouteChildren = {
  AppOrgsOrgIdEditRoute: AppOrgsOrgIdEditRoute,
  AppOrgsOrgIdIndexRoute: AppOrgsOrgIdIndexRoute,
}

const AppOrgsOrgIdRouteRouteWithChildren =
  AppOrgsOrgIdRouteRoute._addFileChildren(AppOrgsOrgIdRouteRouteChildren)

interface AppOrgsRouteRouteChildren {
  AppOrgsOrgIdRouteRoute: typeof AppOrgsOrgIdRouteRouteWithChildren
  AppOrgsAddRoute: typeof AppOrgsAddRoute
  AppOrgsIndexRoute: typeof AppOrgsIndexRoute
}

const AppOrgsRouteRouteChildren: AppOrgsRouteRouteChildren = {
  AppOrgsOrgIdRouteRoute: AppOrgsOrgIdRouteRouteWithChildren,
  AppOrgsAddRoute: AppOrgsAddRoute,
  AppOrgsIndexRoute: AppOrgsIndexRoute,
}

const AppOrgsRouteRouteWithChildren = AppOrgsRouteRoute._addFileChildren(
  AppOrgsRouteRouteChildren,
)

interface AppProvidersProviderIdRouteRouteChildren {
  AppProvidersProviderIdEditRoute: typeof AppProvidersProviderIdEditRoute
  AppProvidersProviderIdIndexRoute: typeof AppProvidersProviderIdIndexRoute
}

const AppProvidersProviderIdRouteRouteChildren: AppProvidersProviderIdRouteRouteChildren =
  {
    AppProvidersProviderIdEditRoute: AppProvidersProviderIdEditRoute,
    AppProvidersProviderIdIndexRoute: AppProvidersProviderIdIndexRoute,
  }

const AppProvidersProviderIdRouteRouteWithChildren =
  AppProvidersProviderIdRouteRoute._addFileChildren(
    AppProvidersProviderIdRouteRouteChildren,
  )

interface AppProvidersRouteRouteChildren {
  AppProvidersProviderIdRouteRoute: typeof AppProvidersProviderIdRouteRouteWithChildren
  AppProvidersAddRoute: typeof AppProvidersAddRoute
  AppProvidersIndexRoute: typeof AppProvidersIndexRoute
}

const AppProvidersRouteRouteChildren: AppProvidersRouteRouteChildren = {
  AppProvidersProviderIdRouteRoute:
    AppProvidersProviderIdRouteRouteWithChildren,
  AppProvidersAddRoute: AppProvidersAddRoute,
  AppProvidersIndexRoute: AppProvidersIndexRoute,
}

const AppProvidersRouteRouteWithChildren =
  AppProvidersRouteRoute._addFileChildren(AppProvidersRouteRouteChildren)

interface AppQuotasQuotaPoolIdRouteRouteChildren {
  AppQuotasQuotaPoolIdEditRoute: typeof AppQuotasQuotaPoolIdEditRoute
  AppQuotasQuotaPoolIdIndexRoute: typeof AppQuotasQuotaPoolIdIndexRoute
}

const AppQuotasQuotaPoolIdRouteRouteChildren: AppQuotasQuotaPoolIdRouteRouteChildren =
  {
    AppQuotasQuotaPoolIdEditRoute: AppQuotasQuotaPoolIdEditRoute,
    AppQuotasQuotaPoolIdIndexRoute: AppQuotasQuotaPoolIdIndexRoute,
  }

const AppQuotasQuotaPoolIdRouteRouteWithChildren =
  AppQuotasQuotaPoolIdRouteRoute._addFileChildren(
    AppQuotasQuotaPoolIdRouteRouteChildren,
  )

interface AppQuotasRouteRouteChildren {
  AppQuotasQuotaPoolIdRouteRoute: typeof AppQuotasQuotaPoolIdRouteRouteWithChildren
  AppQuotasAddRoute: typeof AppQuotasAddRoute
  AppQuotasIndexRoute: typeof AppQuotasIndexRoute
}

const AppQuotasRouteRouteChildren: AppQuotasRouteRouteChildren = {
  AppQuotasQuotaPoolIdRouteRoute: AppQuotasQuotaPoolIdRouteRouteWithChildren,
  AppQuotasAddRoute: AppQuotasAddRoute,
  AppQuotasIndexRoute: AppQuotasIndexRoute,
}

const AppQuotasRouteRouteWithChildren = AppQuotasRouteRoute._addFileChildren(
  AppQuotasRouteRouteChildren,
)

interface AppUsersUserIdRouteRouteChildren {
  AppUsersUserIdEditRoute: typeof AppUsersUserIdEditRoute
}

const AppUsersUserIdRouteRouteChildren: AppUsersUserIdRouteRouteChildren = {
  AppUsersUserIdEditRoute: AppUsersUserIdEditRoute,
}

const AppUsersUserIdRouteRouteWithChildren =
  AppUsersUserIdRouteRoute._addFileChildren(AppUsersUserIdRouteRouteChildren)

interface AppUsersRouteRouteChildren {
  AppUsersUserIdRouteRoute: typeof AppUsersUserIdRouteRouteWithChildren
  AppUsersAddRoute: typeof AppUsersAddRoute
  AppUsersInvitesRoute: typeof AppUsersInvitesRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppUsersRouteRouteChildren: AppUsersRouteRouteChildren = {
  AppUsersUserIdRouteRoute: AppUsersUserIdRouteRouteWithChildren,
  AppUsersAddRoute: AppUsersAddRoute,
  AppUsersInvitesRoute: AppUsersInvitesRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppUsersRouteRouteWithChildren = AppUsersRouteRoute._addFileChildren(
  AppUsersRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAccountRouteRoute: typeof AppAccountRouteRouteWithChildren
  AppChatRouteRoute: typeof AppChatRouteRouteWithChildren
  AppGroupsRouteRoute: typeof AppGroupsRouteRouteWithChildren
  AppHubRouteRoute: typeof AppHubRouteRouteWithChildren
  AppModelsRouteRoute: typeof AppModelsRouteRouteWithChildren
  AppOrgsRouteRoute: typeof AppOrgsRouteRouteWithChildren
  AppProvidersRouteRoute: typeof AppProvidersRouteRouteWithChildren
  AppQuotasRouteRoute: typeof AppQuotasRouteRouteWithChildren
  AppUsersRouteRoute: typeof AppUsersRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRouteRoute: AppAccountRouteRouteWithChildren,
  AppChatRouteRoute: AppChatRouteRouteWithChildren,
  AppGroupsRouteRoute: AppGroupsRouteRouteWithChildren,
  AppHubRouteRoute: AppHubRouteRouteWithChildren,
  AppModelsRouteRoute: AppModelsRouteRouteWithChildren,
  AppOrgsRouteRoute: AppOrgsRouteRouteWithChildren,
  AppProvidersRouteRoute: AppProvidersRouteRouteWithChildren,
  AppQuotasRouteRoute: AppQuotasRouteRouteWithChildren,
  AppUsersRouteRoute: AppUsersRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocSplatRoute: ApiDocSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
