FROM oven/bun:1.3.11-alpine

WORKDIR /app

COPY package.json bun.lock ./
COPY packages/core ./packages/core
COPY packages/schema ./packages/schema
COPY packages/db ./packages/db

WORKDIR /app/packages/db

RUN bun install

CMD ["bun", "run", "migrate"]
