# syntax=docker/dockerfile:1.7

ARG BUN_IMAGE=oven/bun:1.3.13-slim
FROM ${BUN_IMAGE}

WORKDIR /app

COPY package.json bun.lock ./
COPY packages/spice-db ./packages/spice-db
COPY packages/core ./packages/core

WORKDIR /app/packages/spice-db

RUN bun install

USER bun

CMD ["bun", "run", "up"]
