/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PathlessLayoutTouRouteImport } from './routes/_pathlessLayout/tou'
import { Route as PathlessLayoutSelectOrganizationRouteImport } from './routes/_pathlessLayout/select-organization'
import { Route as PathlessLayoutRegisterRouteImport } from './routes/_pathlessLayout/register'
import { Route as PathlessLayoutPrivacyRouteImport } from './routes/_pathlessLayout/privacy'
import { Route as PathlessLayoutLoginRouteImport } from './routes/_pathlessLayout/login'
import { Route as AppUsersRouteRouteImport } from './routes/app/users/route'
import { Route as AppOrgsRouteRouteImport } from './routes/app/orgs/route'
import { Route as AppCoursesRouteRouteImport } from './routes/app/courses/route'
import { Route as AppChatRouteRouteImport } from './routes/app/chat/route'
import { Route as AppBotsRouteRouteImport } from './routes/app/bots/route'
import { Route as AppBlocksRouteRouteImport } from './routes/app/blocks/route'
import { Route as AppAssetsRouteRouteImport } from './routes/app/assets/route'
import { Route as AppAccountRouteRouteImport } from './routes/app/account/route'
import { Route as AppUsersIndexRouteImport } from './routes/app/users/index'
import { Route as AppOrgsIndexRouteImport } from './routes/app/orgs/index'
import { Route as AppCoursesIndexRouteImport } from './routes/app/courses/index'
import { Route as AppChatIndexRouteImport } from './routes/app/chat/index'
import { Route as AppBotsIndexRouteImport } from './routes/app/bots/index'
import { Route as AppBlocksIndexRouteImport } from './routes/app/blocks/index'
import { Route as AppAssetsIndexRouteImport } from './routes/app/assets/index'
import { Route as AppAccountIndexRouteImport } from './routes/app/account/index'
import { Route as AppUsersInvitesRouteImport } from './routes/app/users/invites'
import { Route as AppUsersAddRouteImport } from './routes/app/users/add'
import { Route as AppOrgsAddRouteImport } from './routes/app/orgs/add'
import { Route as AppCoursesAddRouteImport } from './routes/app/courses/add'
import { Route as AppChatSetupRouteImport } from './routes/app/chat/setup'
import { Route as AppBotsAddRouteImport } from './routes/app/bots/add'
import { Route as AppBlocksAddRouteImport } from './routes/app/blocks/add'
import { Route as AppAssetsPlaygroundRouteImport } from './routes/app/assets/playground'
import { Route as AppAssetsAddRouteImport } from './routes/app/assets/add'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiDocSplatRouteImport } from './routes/api/doc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppUsersUserIdRouteRouteImport } from './routes/app/users/$userId/route'
import { Route as AppOrgsOrgIdRouteRouteImport } from './routes/app/orgs/$orgId/route'
import { Route as AppCoursesCourseIdRouteRouteImport } from './routes/app/courses/$courseId/route'
import { Route as AppBotsBotIdRouteRouteImport } from './routes/app/bots/$botId/route'
import { Route as AppBlocksBlockIdRouteRouteImport } from './routes/app/blocks/$blockId/route'
import { Route as AppAssetsAssetIdRouteRouteImport } from './routes/app/assets/$assetId/route'
import { Route as AppOrgsOrgIdIndexRouteImport } from './routes/app/orgs/$orgId/index'
import { Route as AppCoursesCourseIdIndexRouteImport } from './routes/app/courses/$courseId/index'
import { Route as AppChatChatIdIndexRouteImport } from './routes/app/chat/$chatId/index'
import { Route as AppBotsBotIdIndexRouteImport } from './routes/app/bots/$botId/index'
import { Route as AppBlocksBlockIdIndexRouteImport } from './routes/app/blocks/$blockId/index'
import { Route as AppAssetsAssetIdIndexRouteImport } from './routes/app/assets/$assetId/index'
import { Route as AppUsersUserIdEditRouteImport } from './routes/app/users/$userId/edit'
import { Route as AppOrgsOrgIdEditRouteImport } from './routes/app/orgs/$orgId/edit'
import { Route as AppCoursesCourseIdEditRouteImport } from './routes/app/courses/$courseId/edit'
import { Route as AppBotsBotIdEditRouteImport } from './routes/app/bots/$botId/edit'
import { Route as AppBlocksBlockIdPointsRouteImport } from './routes/app/blocks/$blockId/points'
import { Route as AppBlocksBlockIdEditRouteImport } from './routes/app/blocks/$blockId/edit'
import { Route as AppAssetsAssetIdEditRouteImport } from './routes/app/assets/$assetId/edit'
import { Route as AppOrgsOrgIdProvidersRouteRouteImport } from './routes/app/orgs/$orgId/providers/route'
import { Route as AppOrgsOrgIdProvidersIndexRouteImport } from './routes/app/orgs/$orgId/providers/index'
import { Route as AppOrgsOrgIdProvidersAddRouteImport } from './routes/app/orgs/$orgId/providers/add'
import { Route as AppOrgsOrgIdProvidersProviderSlugRouteRouteImport } from './routes/app/orgs/$orgId/providers/$providerSlug/route'
import { Route as AppOrgsOrgIdProvidersProviderSlugIndexRouteImport } from './routes/app/orgs/$orgId/providers/$providerSlug/index'
import { Route as AppOrgsOrgIdProvidersProviderSlugEditRouteImport } from './routes/app/orgs/$orgId/providers/$providerSlug/edit'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PathlessLayoutTouRoute = PathlessLayoutTouRouteImport.update({
  id: '/tou',
  path: '/tou',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutSelectOrganizationRoute =
  PathlessLayoutSelectOrganizationRouteImport.update({
    id: '/select-organization',
    path: '/select-organization',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutRegisterRoute = PathlessLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutPrivacyRoute = PathlessLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutLoginRoute = PathlessLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const AppUsersRouteRoute = AppUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrgsRouteRoute = AppOrgsRouteRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesRouteRoute = AppCoursesRouteRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRouteRoute = AppChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBotsRouteRoute = AppBotsRouteRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBlocksRouteRoute = AppBlocksRouteRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssetsRouteRoute = AppAssetsRouteRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRouteRoute = AppAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppOrgsIndexRoute = AppOrgsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgsRouteRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRouteRoute,
} as any)
const AppBotsIndexRoute = AppBotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBotsRouteRoute,
} as any)
const AppBlocksIndexRoute = AppBlocksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBlocksRouteRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAssetsRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppUsersInvitesRoute = AppUsersInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppUsersAddRoute = AppUsersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppOrgsAddRoute = AppOrgsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppOrgsRouteRoute,
} as any)
const AppCoursesAddRoute = AppCoursesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppChatSetupRoute = AppChatSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppChatRouteRoute,
} as any)
const AppBotsAddRoute = AppBotsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppBotsRouteRoute,
} as any)
const AppBlocksAddRoute = AppBlocksAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppBlocksRouteRoute,
} as any)
const AppAssetsPlaygroundRoute = AppAssetsPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppAssetsRouteRoute,
} as any)
const AppAssetsAddRoute = AppAssetsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppAssetsRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocSplatRoute = ApiDocSplatRouteImport.update({
  id: '/api/doc/$',
  path: '/api/doc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersUserIdRouteRoute = AppUsersUserIdRouteRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppOrgsOrgIdRouteRoute = AppOrgsOrgIdRouteRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AppOrgsRouteRoute,
} as any)
const AppCoursesCourseIdRouteRoute = AppCoursesCourseIdRouteRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppCoursesRouteRoute,
} as any)
const AppBotsBotIdRouteRoute = AppBotsBotIdRouteRouteImport.update({
  id: '/$botId',
  path: '/$botId',
  getParentRoute: () => AppBotsRouteRoute,
} as any)
const AppBlocksBlockIdRouteRoute = AppBlocksBlockIdRouteRouteImport.update({
  id: '/$blockId',
  path: '/$blockId',
  getParentRoute: () => AppBlocksRouteRoute,
} as any)
const AppAssetsAssetIdRouteRoute = AppAssetsAssetIdRouteRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => AppAssetsRouteRoute,
} as any)
const AppOrgsOrgIdIndexRoute = AppOrgsOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgsOrgIdRouteRoute,
} as any)
const AppCoursesCourseIdIndexRoute = AppCoursesCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesCourseIdRouteRoute,
} as any)
const AppChatChatIdIndexRoute = AppChatChatIdIndexRouteImport.update({
  id: '/$chatId/',
  path: '/$chatId/',
  getParentRoute: () => AppChatRouteRoute,
} as any)
const AppBotsBotIdIndexRoute = AppBotsBotIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBotsBotIdRouteRoute,
} as any)
const AppBlocksBlockIdIndexRoute = AppBlocksBlockIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBlocksBlockIdRouteRoute,
} as any)
const AppAssetsAssetIdIndexRoute = AppAssetsAssetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAssetsAssetIdRouteRoute,
} as any)
const AppUsersUserIdEditRoute = AppUsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppUsersUserIdRouteRoute,
} as any)
const AppOrgsOrgIdEditRoute = AppOrgsOrgIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppOrgsOrgIdRouteRoute,
} as any)
const AppCoursesCourseIdEditRoute = AppCoursesCourseIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppCoursesCourseIdRouteRoute,
} as any)
const AppBotsBotIdEditRoute = AppBotsBotIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppBotsBotIdRouteRoute,
} as any)
const AppBlocksBlockIdPointsRoute = AppBlocksBlockIdPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AppBlocksBlockIdRouteRoute,
} as any)
const AppBlocksBlockIdEditRoute = AppBlocksBlockIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppBlocksBlockIdRouteRoute,
} as any)
const AppAssetsAssetIdEditRoute = AppAssetsAssetIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppAssetsAssetIdRouteRoute,
} as any)
const AppOrgsOrgIdProvidersRouteRoute =
  AppOrgsOrgIdProvidersRouteRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AppOrgsOrgIdRouteRoute,
  } as any)
const AppOrgsOrgIdProvidersIndexRoute =
  AppOrgsOrgIdProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrgsOrgIdProvidersRouteRoute,
  } as any)
const AppOrgsOrgIdProvidersAddRoute =
  AppOrgsOrgIdProvidersAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AppOrgsOrgIdProvidersRouteRoute,
  } as any)
const AppOrgsOrgIdProvidersProviderSlugRouteRoute =
  AppOrgsOrgIdProvidersProviderSlugRouteRouteImport.update({
    id: '/$providerSlug',
    path: '/$providerSlug',
    getParentRoute: () => AppOrgsOrgIdProvidersRouteRoute,
  } as any)
const AppOrgsOrgIdProvidersProviderSlugIndexRoute =
  AppOrgsOrgIdProvidersProviderSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrgsOrgIdProvidersProviderSlugRouteRoute,
  } as any)
const AppOrgsOrgIdProvidersProviderSlugEditRoute =
  AppOrgsOrgIdProvidersProviderSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppOrgsOrgIdProvidersProviderSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/account': typeof AppAccountRouteRouteWithChildren
  '/app/assets': typeof AppAssetsRouteRouteWithChildren
  '/app/blocks': typeof AppBlocksRouteRouteWithChildren
  '/app/bots': typeof AppBotsRouteRouteWithChildren
  '/app/chat': typeof AppChatRouteRouteWithChildren
  '/app/courses': typeof AppCoursesRouteRouteWithChildren
  '/app/orgs': typeof AppOrgsRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRouteWithChildren
  '/login': typeof PathlessLayoutLoginRoute
  '/privacy': typeof PathlessLayoutPrivacyRoute
  '/register': typeof PathlessLayoutRegisterRoute
  '/select-organization': typeof PathlessLayoutSelectOrganizationRoute
  '/tou': typeof PathlessLayoutTouRoute
  '/app/': typeof AppIndexRoute
  '/app/assets/$assetId': typeof AppAssetsAssetIdRouteRouteWithChildren
  '/app/blocks/$blockId': typeof AppBlocksBlockIdRouteRouteWithChildren
  '/app/bots/$botId': typeof AppBotsBotIdRouteRouteWithChildren
  '/app/courses/$courseId': typeof AppCoursesCourseIdRouteRouteWithChildren
  '/app/orgs/$orgId': typeof AppOrgsOrgIdRouteRouteWithChildren
  '/app/users/$userId': typeof AppUsersUserIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/doc/$': typeof ApiDocSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/assets/add': typeof AppAssetsAddRoute
  '/app/assets/playground': typeof AppAssetsPlaygroundRoute
  '/app/blocks/add': typeof AppBlocksAddRoute
  '/app/bots/add': typeof AppBotsAddRoute
  '/app/chat/setup': typeof AppChatSetupRoute
  '/app/courses/add': typeof AppCoursesAddRoute
  '/app/orgs/add': typeof AppOrgsAddRoute
  '/app/users/add': typeof AppUsersAddRoute
  '/app/users/invites': typeof AppUsersInvitesRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/assets/': typeof AppAssetsIndexRoute
  '/app/blocks/': typeof AppBlocksIndexRoute
  '/app/bots/': typeof AppBotsIndexRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/courses/': typeof AppCoursesIndexRoute
  '/app/orgs/': typeof AppOrgsIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/orgs/$orgId/providers': typeof AppOrgsOrgIdProvidersRouteRouteWithChildren
  '/app/assets/$assetId/edit': typeof AppAssetsAssetIdEditRoute
  '/app/blocks/$blockId/edit': typeof AppBlocksBlockIdEditRoute
  '/app/blocks/$blockId/points': typeof AppBlocksBlockIdPointsRoute
  '/app/bots/$botId/edit': typeof AppBotsBotIdEditRoute
  '/app/courses/$courseId/edit': typeof AppCoursesCourseIdEditRoute
  '/app/orgs/$orgId/edit': typeof AppOrgsOrgIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/assets/$assetId/': typeof AppAssetsAssetIdIndexRoute
  '/app/blocks/$blockId/': typeof AppBlocksBlockIdIndexRoute
  '/app/bots/$botId/': typeof AppBotsBotIdIndexRoute
  '/app/chat/$chatId/': typeof AppChatChatIdIndexRoute
  '/app/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/app/orgs/$orgId/': typeof AppOrgsOrgIdIndexRoute
  '/app/orgs/$orgId/providers/$providerSlug': typeof AppOrgsOrgIdProvidersProviderSlugRouteRouteWithChildren
  '/app/orgs/$orgId/providers/add': typeof AppOrgsOrgIdProvidersAddRoute
  '/app/orgs/$orgId/providers/': typeof AppOrgsOrgIdProvidersIndexRoute
  '/app/orgs/$orgId/providers/$providerSlug/edit': typeof AppOrgsOrgIdProvidersProviderSlugEditRoute
  '/app/orgs/$orgId/providers/$providerSlug/': typeof AppOrgsOrgIdProvidersProviderSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PathlessLayoutLoginRoute
  '/privacy': typeof PathlessLayoutPrivacyRoute
  '/register': typeof PathlessLayoutRegisterRoute
  '/select-organization': typeof PathlessLayoutSelectOrganizationRoute
  '/tou': typeof PathlessLayoutTouRoute
  '/app': typeof AppIndexRoute
  '/app/users/$userId': typeof AppUsersUserIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/doc/$': typeof ApiDocSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/assets/add': typeof AppAssetsAddRoute
  '/app/assets/playground': typeof AppAssetsPlaygroundRoute
  '/app/blocks/add': typeof AppBlocksAddRoute
  '/app/bots/add': typeof AppBotsAddRoute
  '/app/chat/setup': typeof AppChatSetupRoute
  '/app/courses/add': typeof AppCoursesAddRoute
  '/app/orgs/add': typeof AppOrgsAddRoute
  '/app/users/add': typeof AppUsersAddRoute
  '/app/users/invites': typeof AppUsersInvitesRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/assets': typeof AppAssetsIndexRoute
  '/app/blocks': typeof AppBlocksIndexRoute
  '/app/bots': typeof AppBotsIndexRoute
  '/app/chat': typeof AppChatIndexRoute
  '/app/courses': typeof AppCoursesIndexRoute
  '/app/orgs': typeof AppOrgsIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/assets/$assetId/edit': typeof AppAssetsAssetIdEditRoute
  '/app/blocks/$blockId/edit': typeof AppBlocksBlockIdEditRoute
  '/app/blocks/$blockId/points': typeof AppBlocksBlockIdPointsRoute
  '/app/bots/$botId/edit': typeof AppBotsBotIdEditRoute
  '/app/courses/$courseId/edit': typeof AppCoursesCourseIdEditRoute
  '/app/orgs/$orgId/edit': typeof AppOrgsOrgIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/assets/$assetId': typeof AppAssetsAssetIdIndexRoute
  '/app/blocks/$blockId': typeof AppBlocksBlockIdIndexRoute
  '/app/bots/$botId': typeof AppBotsBotIdIndexRoute
  '/app/chat/$chatId': typeof AppChatChatIdIndexRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdIndexRoute
  '/app/orgs/$orgId': typeof AppOrgsOrgIdIndexRoute
  '/app/orgs/$orgId/providers/add': typeof AppOrgsOrgIdProvidersAddRoute
  '/app/orgs/$orgId/providers': typeof AppOrgsOrgIdProvidersIndexRoute
  '/app/orgs/$orgId/providers/$providerSlug/edit': typeof AppOrgsOrgIdProvidersProviderSlugEditRoute
  '/app/orgs/$orgId/providers/$providerSlug': typeof AppOrgsOrgIdProvidersProviderSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/account': typeof AppAccountRouteRouteWithChildren
  '/app/assets': typeof AppAssetsRouteRouteWithChildren
  '/app/blocks': typeof AppBlocksRouteRouteWithChildren
  '/app/bots': typeof AppBotsRouteRouteWithChildren
  '/app/chat': typeof AppChatRouteRouteWithChildren
  '/app/courses': typeof AppCoursesRouteRouteWithChildren
  '/app/orgs': typeof AppOrgsRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRouteWithChildren
  '/_pathlessLayout/login': typeof PathlessLayoutLoginRoute
  '/_pathlessLayout/privacy': typeof PathlessLayoutPrivacyRoute
  '/_pathlessLayout/register': typeof PathlessLayoutRegisterRoute
  '/_pathlessLayout/select-organization': typeof PathlessLayoutSelectOrganizationRoute
  '/_pathlessLayout/tou': typeof PathlessLayoutTouRoute
  '/app/': typeof AppIndexRoute
  '/app/assets/$assetId': typeof AppAssetsAssetIdRouteRouteWithChildren
  '/app/blocks/$blockId': typeof AppBlocksBlockIdRouteRouteWithChildren
  '/app/bots/$botId': typeof AppBotsBotIdRouteRouteWithChildren
  '/app/courses/$courseId': typeof AppCoursesCourseIdRouteRouteWithChildren
  '/app/orgs/$orgId': typeof AppOrgsOrgIdRouteRouteWithChildren
  '/app/users/$userId': typeof AppUsersUserIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/doc/$': typeof ApiDocSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/assets/add': typeof AppAssetsAddRoute
  '/app/assets/playground': typeof AppAssetsPlaygroundRoute
  '/app/blocks/add': typeof AppBlocksAddRoute
  '/app/bots/add': typeof AppBotsAddRoute
  '/app/chat/setup': typeof AppChatSetupRoute
  '/app/courses/add': typeof AppCoursesAddRoute
  '/app/orgs/add': typeof AppOrgsAddRoute
  '/app/users/add': typeof AppUsersAddRoute
  '/app/users/invites': typeof AppUsersInvitesRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/assets/': typeof AppAssetsIndexRoute
  '/app/blocks/': typeof AppBlocksIndexRoute
  '/app/bots/': typeof AppBotsIndexRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/courses/': typeof AppCoursesIndexRoute
  '/app/orgs/': typeof AppOrgsIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/orgs/$orgId/providers': typeof AppOrgsOrgIdProvidersRouteRouteWithChildren
  '/app/assets/$assetId/edit': typeof AppAssetsAssetIdEditRoute
  '/app/blocks/$blockId/edit': typeof AppBlocksBlockIdEditRoute
  '/app/blocks/$blockId/points': typeof AppBlocksBlockIdPointsRoute
  '/app/bots/$botId/edit': typeof AppBotsBotIdEditRoute
  '/app/courses/$courseId/edit': typeof AppCoursesCourseIdEditRoute
  '/app/orgs/$orgId/edit': typeof AppOrgsOrgIdEditRoute
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/assets/$assetId/': typeof AppAssetsAssetIdIndexRoute
  '/app/blocks/$blockId/': typeof AppBlocksBlockIdIndexRoute
  '/app/bots/$botId/': typeof AppBotsBotIdIndexRoute
  '/app/chat/$chatId/': typeof AppChatChatIdIndexRoute
  '/app/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/app/orgs/$orgId/': typeof AppOrgsOrgIdIndexRoute
  '/app/orgs/$orgId/providers/$providerSlug': typeof AppOrgsOrgIdProvidersProviderSlugRouteRouteWithChildren
  '/app/orgs/$orgId/providers/add': typeof AppOrgsOrgIdProvidersAddRoute
  '/app/orgs/$orgId/providers/': typeof AppOrgsOrgIdProvidersIndexRoute
  '/app/orgs/$orgId/providers/$providerSlug/edit': typeof AppOrgsOrgIdProvidersProviderSlugEditRoute
  '/app/orgs/$orgId/providers/$providerSlug/': typeof AppOrgsOrgIdProvidersProviderSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/account'
    | '/app/assets'
    | '/app/blocks'
    | '/app/bots'
    | '/app/chat'
    | '/app/courses'
    | '/app/orgs'
    | '/app/users'
    | '/login'
    | '/privacy'
    | '/register'
    | '/select-organization'
    | '/tou'
    | '/app/'
    | '/app/assets/$assetId'
    | '/app/blocks/$blockId'
    | '/app/bots/$botId'
    | '/app/courses/$courseId'
    | '/app/orgs/$orgId'
    | '/app/users/$userId'
    | '/api/auth/$'
    | '/api/doc/$'
    | '/api/rpc/$'
    | '/app/assets/add'
    | '/app/assets/playground'
    | '/app/blocks/add'
    | '/app/bots/add'
    | '/app/chat/setup'
    | '/app/courses/add'
    | '/app/orgs/add'
    | '/app/users/add'
    | '/app/users/invites'
    | '/app/account/'
    | '/app/assets/'
    | '/app/blocks/'
    | '/app/bots/'
    | '/app/chat/'
    | '/app/courses/'
    | '/app/orgs/'
    | '/app/users/'
    | '/app/orgs/$orgId/providers'
    | '/app/assets/$assetId/edit'
    | '/app/blocks/$blockId/edit'
    | '/app/blocks/$blockId/points'
    | '/app/bots/$botId/edit'
    | '/app/courses/$courseId/edit'
    | '/app/orgs/$orgId/edit'
    | '/app/users/$userId/edit'
    | '/app/assets/$assetId/'
    | '/app/blocks/$blockId/'
    | '/app/bots/$botId/'
    | '/app/chat/$chatId/'
    | '/app/courses/$courseId/'
    | '/app/orgs/$orgId/'
    | '/app/orgs/$orgId/providers/$providerSlug'
    | '/app/orgs/$orgId/providers/add'
    | '/app/orgs/$orgId/providers/'
    | '/app/orgs/$orgId/providers/$providerSlug/edit'
    | '/app/orgs/$orgId/providers/$providerSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/register'
    | '/select-organization'
    | '/tou'
    | '/app'
    | '/app/users/$userId'
    | '/api/auth/$'
    | '/api/doc/$'
    | '/api/rpc/$'
    | '/app/assets/add'
    | '/app/assets/playground'
    | '/app/blocks/add'
    | '/app/bots/add'
    | '/app/chat/setup'
    | '/app/courses/add'
    | '/app/orgs/add'
    | '/app/users/add'
    | '/app/users/invites'
    | '/app/account'
    | '/app/assets'
    | '/app/blocks'
    | '/app/bots'
    | '/app/chat'
    | '/app/courses'
    | '/app/orgs'
    | '/app/users'
    | '/app/assets/$assetId/edit'
    | '/app/blocks/$blockId/edit'
    | '/app/blocks/$blockId/points'
    | '/app/bots/$botId/edit'
    | '/app/courses/$courseId/edit'
    | '/app/orgs/$orgId/edit'
    | '/app/users/$userId/edit'
    | '/app/assets/$assetId'
    | '/app/blocks/$blockId'
    | '/app/bots/$botId'
    | '/app/chat/$chatId'
    | '/app/courses/$courseId'
    | '/app/orgs/$orgId'
    | '/app/orgs/$orgId/providers/add'
    | '/app/orgs/$orgId/providers'
    | '/app/orgs/$orgId/providers/$providerSlug/edit'
    | '/app/orgs/$orgId/providers/$providerSlug'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/app'
    | '/app/account'
    | '/app/assets'
    | '/app/blocks'
    | '/app/bots'
    | '/app/chat'
    | '/app/courses'
    | '/app/orgs'
    | '/app/users'
    | '/_pathlessLayout/login'
    | '/_pathlessLayout/privacy'
    | '/_pathlessLayout/register'
    | '/_pathlessLayout/select-organization'
    | '/_pathlessLayout/tou'
    | '/app/'
    | '/app/assets/$assetId'
    | '/app/blocks/$blockId'
    | '/app/bots/$botId'
    | '/app/courses/$courseId'
    | '/app/orgs/$orgId'
    | '/app/users/$userId'
    | '/api/auth/$'
    | '/api/doc/$'
    | '/api/rpc/$'
    | '/app/assets/add'
    | '/app/assets/playground'
    | '/app/blocks/add'
    | '/app/bots/add'
    | '/app/chat/setup'
    | '/app/courses/add'
    | '/app/orgs/add'
    | '/app/users/add'
    | '/app/users/invites'
    | '/app/account/'
    | '/app/assets/'
    | '/app/blocks/'
    | '/app/bots/'
    | '/app/chat/'
    | '/app/courses/'
    | '/app/orgs/'
    | '/app/users/'
    | '/app/orgs/$orgId/providers'
    | '/app/assets/$assetId/edit'
    | '/app/blocks/$blockId/edit'
    | '/app/blocks/$blockId/points'
    | '/app/bots/$botId/edit'
    | '/app/courses/$courseId/edit'
    | '/app/orgs/$orgId/edit'
    | '/app/users/$userId/edit'
    | '/app/assets/$assetId/'
    | '/app/blocks/$blockId/'
    | '/app/bots/$botId/'
    | '/app/chat/$chatId/'
    | '/app/courses/$courseId/'
    | '/app/orgs/$orgId/'
    | '/app/orgs/$orgId/providers/$providerSlug'
    | '/app/orgs/$orgId/providers/add'
    | '/app/orgs/$orgId/providers/'
    | '/app/orgs/$orgId/providers/$providerSlug/edit'
    | '/app/orgs/$orgId/providers/$providerSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocSplatRoute: typeof ApiDocSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_pathlessLayout/tou': {
      id: '/_pathlessLayout/tou'
      path: '/tou'
      fullPath: '/tou'
      preLoaderRoute: typeof PathlessLayoutTouRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/select-organization': {
      id: '/_pathlessLayout/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof PathlessLayoutSelectOrganizationRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/register': {
      id: '/_pathlessLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PathlessLayoutRegisterRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/privacy': {
      id: '/_pathlessLayout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PathlessLayoutPrivacyRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/login': {
      id: '/_pathlessLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PathlessLayoutLoginRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orgs': {
      id: '/app/orgs'
      path: '/orgs'
      fullPath: '/app/orgs'
      preLoaderRoute: typeof AppOrgsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/courses': {
      id: '/app/courses'
      path: '/courses'
      fullPath: '/app/courses'
      preLoaderRoute: typeof AppCoursesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/bots': {
      id: '/app/bots'
      path: '/bots'
      fullPath: '/app/bots'
      preLoaderRoute: typeof AppBotsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/blocks': {
      id: '/app/blocks'
      path: '/blocks'
      fullPath: '/app/blocks'
      preLoaderRoute: typeof AppBlocksRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/orgs/': {
      id: '/app/orgs/'
      path: '/'
      fullPath: '/app/orgs/'
      preLoaderRoute: typeof AppOrgsIndexRouteImport
      parentRoute: typeof AppOrgsRouteRoute
    }
    '/app/courses/': {
      id: '/app/courses/'
      path: '/'
      fullPath: '/app/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRouteRoute
    }
    '/app/bots/': {
      id: '/app/bots/'
      path: '/'
      fullPath: '/app/bots/'
      preLoaderRoute: typeof AppBotsIndexRouteImport
      parentRoute: typeof AppBotsRouteRoute
    }
    '/app/blocks/': {
      id: '/app/blocks/'
      path: '/'
      fullPath: '/app/blocks/'
      preLoaderRoute: typeof AppBlocksIndexRouteImport
      parentRoute: typeof AppBlocksRouteRoute
    }
    '/app/assets/': {
      id: '/app/assets/'
      path: '/'
      fullPath: '/app/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppAssetsRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/app/users/invites': {
      id: '/app/users/invites'
      path: '/invites'
      fullPath: '/app/users/invites'
      preLoaderRoute: typeof AppUsersInvitesRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/users/add': {
      id: '/app/users/add'
      path: '/add'
      fullPath: '/app/users/add'
      preLoaderRoute: typeof AppUsersAddRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/orgs/add': {
      id: '/app/orgs/add'
      path: '/add'
      fullPath: '/app/orgs/add'
      preLoaderRoute: typeof AppOrgsAddRouteImport
      parentRoute: typeof AppOrgsRouteRoute
    }
    '/app/courses/add': {
      id: '/app/courses/add'
      path: '/add'
      fullPath: '/app/courses/add'
      preLoaderRoute: typeof AppCoursesAddRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/app/chat/setup': {
      id: '/app/chat/setup'
      path: '/setup'
      fullPath: '/app/chat/setup'
      preLoaderRoute: typeof AppChatSetupRouteImport
      parentRoute: typeof AppChatRouteRoute
    }
    '/app/bots/add': {
      id: '/app/bots/add'
      path: '/add'
      fullPath: '/app/bots/add'
      preLoaderRoute: typeof AppBotsAddRouteImport
      parentRoute: typeof AppBotsRouteRoute
    }
    '/app/blocks/add': {
      id: '/app/blocks/add'
      path: '/add'
      fullPath: '/app/blocks/add'
      preLoaderRoute: typeof AppBlocksAddRouteImport
      parentRoute: typeof AppBlocksRouteRoute
    }
    '/app/assets/playground': {
      id: '/app/assets/playground'
      path: '/playground'
      fullPath: '/app/assets/playground'
      preLoaderRoute: typeof AppAssetsPlaygroundRouteImport
      parentRoute: typeof AppAssetsRouteRoute
    }
    '/app/assets/add': {
      id: '/app/assets/add'
      path: '/add'
      fullPath: '/app/assets/add'
      preLoaderRoute: typeof AppAssetsAddRouteImport
      parentRoute: typeof AppAssetsRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc/$': {
      id: '/api/doc/$'
      path: '/api/doc/$'
      fullPath: '/api/doc/$'
      preLoaderRoute: typeof ApiDocSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users/$userId': {
      id: '/app/users/$userId'
      path: '/$userId'
      fullPath: '/app/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/orgs/$orgId': {
      id: '/app/orgs/$orgId'
      path: '/$orgId'
      fullPath: '/app/orgs/$orgId'
      preLoaderRoute: typeof AppOrgsOrgIdRouteRouteImport
      parentRoute: typeof AppOrgsRouteRoute
    }
    '/app/courses/$courseId': {
      id: '/app/courses/$courseId'
      path: '/$courseId'
      fullPath: '/app/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteRouteImport
      parentRoute: typeof AppCoursesRouteRoute
    }
    '/app/bots/$botId': {
      id: '/app/bots/$botId'
      path: '/$botId'
      fullPath: '/app/bots/$botId'
      preLoaderRoute: typeof AppBotsBotIdRouteRouteImport
      parentRoute: typeof AppBotsRouteRoute
    }
    '/app/blocks/$blockId': {
      id: '/app/blocks/$blockId'
      path: '/$blockId'
      fullPath: '/app/blocks/$blockId'
      preLoaderRoute: typeof AppBlocksBlockIdRouteRouteImport
      parentRoute: typeof AppBlocksRouteRoute
    }
    '/app/assets/$assetId': {
      id: '/app/assets/$assetId'
      path: '/$assetId'
      fullPath: '/app/assets/$assetId'
      preLoaderRoute: typeof AppAssetsAssetIdRouteRouteImport
      parentRoute: typeof AppAssetsRouteRoute
    }
    '/app/orgs/$orgId/': {
      id: '/app/orgs/$orgId/'
      path: '/'
      fullPath: '/app/orgs/$orgId/'
      preLoaderRoute: typeof AppOrgsOrgIdIndexRouteImport
      parentRoute: typeof AppOrgsOrgIdRouteRoute
    }
    '/app/courses/$courseId/': {
      id: '/app/courses/$courseId/'
      path: '/'
      fullPath: '/app/courses/$courseId/'
      preLoaderRoute: typeof AppCoursesCourseIdIndexRouteImport
      parentRoute: typeof AppCoursesCourseIdRouteRoute
    }
    '/app/chat/$chatId/': {
      id: '/app/chat/$chatId/'
      path: '/$chatId'
      fullPath: '/app/chat/$chatId/'
      preLoaderRoute: typeof AppChatChatIdIndexRouteImport
      parentRoute: typeof AppChatRouteRoute
    }
    '/app/bots/$botId/': {
      id: '/app/bots/$botId/'
      path: '/'
      fullPath: '/app/bots/$botId/'
      preLoaderRoute: typeof AppBotsBotIdIndexRouteImport
      parentRoute: typeof AppBotsBotIdRouteRoute
    }
    '/app/blocks/$blockId/': {
      id: '/app/blocks/$blockId/'
      path: '/'
      fullPath: '/app/blocks/$blockId/'
      preLoaderRoute: typeof AppBlocksBlockIdIndexRouteImport
      parentRoute: typeof AppBlocksBlockIdRouteRoute
    }
    '/app/assets/$assetId/': {
      id: '/app/assets/$assetId/'
      path: '/'
      fullPath: '/app/assets/$assetId/'
      preLoaderRoute: typeof AppAssetsAssetIdIndexRouteImport
      parentRoute: typeof AppAssetsAssetIdRouteRoute
    }
    '/app/users/$userId/edit': {
      id: '/app/users/$userId/edit'
      path: '/edit'
      fullPath: '/app/users/$userId/edit'
      preLoaderRoute: typeof AppUsersUserIdEditRouteImport
      parentRoute: typeof AppUsersUserIdRouteRoute
    }
    '/app/orgs/$orgId/edit': {
      id: '/app/orgs/$orgId/edit'
      path: '/edit'
      fullPath: '/app/orgs/$orgId/edit'
      preLoaderRoute: typeof AppOrgsOrgIdEditRouteImport
      parentRoute: typeof AppOrgsOrgIdRouteRoute
    }
    '/app/courses/$courseId/edit': {
      id: '/app/courses/$courseId/edit'
      path: '/edit'
      fullPath: '/app/courses/$courseId/edit'
      preLoaderRoute: typeof AppCoursesCourseIdEditRouteImport
      parentRoute: typeof AppCoursesCourseIdRouteRoute
    }
    '/app/bots/$botId/edit': {
      id: '/app/bots/$botId/edit'
      path: '/edit'
      fullPath: '/app/bots/$botId/edit'
      preLoaderRoute: typeof AppBotsBotIdEditRouteImport
      parentRoute: typeof AppBotsBotIdRouteRoute
    }
    '/app/blocks/$blockId/points': {
      id: '/app/blocks/$blockId/points'
      path: '/points'
      fullPath: '/app/blocks/$blockId/points'
      preLoaderRoute: typeof AppBlocksBlockIdPointsRouteImport
      parentRoute: typeof AppBlocksBlockIdRouteRoute
    }
    '/app/blocks/$blockId/edit': {
      id: '/app/blocks/$blockId/edit'
      path: '/edit'
      fullPath: '/app/blocks/$blockId/edit'
      preLoaderRoute: typeof AppBlocksBlockIdEditRouteImport
      parentRoute: typeof AppBlocksBlockIdRouteRoute
    }
    '/app/assets/$assetId/edit': {
      id: '/app/assets/$assetId/edit'
      path: '/edit'
      fullPath: '/app/assets/$assetId/edit'
      preLoaderRoute: typeof AppAssetsAssetIdEditRouteImport
      parentRoute: typeof AppAssetsAssetIdRouteRoute
    }
    '/app/orgs/$orgId/providers': {
      id: '/app/orgs/$orgId/providers'
      path: '/providers'
      fullPath: '/app/orgs/$orgId/providers'
      preLoaderRoute: typeof AppOrgsOrgIdProvidersRouteRouteImport
      parentRoute: typeof AppOrgsOrgIdRouteRoute
    }
    '/app/orgs/$orgId/providers/': {
      id: '/app/orgs/$orgId/providers/'
      path: '/'
      fullPath: '/app/orgs/$orgId/providers/'
      preLoaderRoute: typeof AppOrgsOrgIdProvidersIndexRouteImport
      parentRoute: typeof AppOrgsOrgIdProvidersRouteRoute
    }
    '/app/orgs/$orgId/providers/add': {
      id: '/app/orgs/$orgId/providers/add'
      path: '/add'
      fullPath: '/app/orgs/$orgId/providers/add'
      preLoaderRoute: typeof AppOrgsOrgIdProvidersAddRouteImport
      parentRoute: typeof AppOrgsOrgIdProvidersRouteRoute
    }
    '/app/orgs/$orgId/providers/$providerSlug': {
      id: '/app/orgs/$orgId/providers/$providerSlug'
      path: '/$providerSlug'
      fullPath: '/app/orgs/$orgId/providers/$providerSlug'
      preLoaderRoute: typeof AppOrgsOrgIdProvidersProviderSlugRouteRouteImport
      parentRoute: typeof AppOrgsOrgIdProvidersRouteRoute
    }
    '/app/orgs/$orgId/providers/$providerSlug/': {
      id: '/app/orgs/$orgId/providers/$providerSlug/'
      path: '/'
      fullPath: '/app/orgs/$orgId/providers/$providerSlug/'
      preLoaderRoute: typeof AppOrgsOrgIdProvidersProviderSlugIndexRouteImport
      parentRoute: typeof AppOrgsOrgIdProvidersProviderSlugRouteRoute
    }
    '/app/orgs/$orgId/providers/$providerSlug/edit': {
      id: '/app/orgs/$orgId/providers/$providerSlug/edit'
      path: '/edit'
      fullPath: '/app/orgs/$orgId/providers/$providerSlug/edit'
      preLoaderRoute: typeof AppOrgsOrgIdProvidersProviderSlugEditRouteImport
      parentRoute: typeof AppOrgsOrgIdProvidersProviderSlugRouteRoute
    }
  }
}

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutLoginRoute: typeof PathlessLayoutLoginRoute
  PathlessLayoutPrivacyRoute: typeof PathlessLayoutPrivacyRoute
  PathlessLayoutRegisterRoute: typeof PathlessLayoutRegisterRoute
  PathlessLayoutSelectOrganizationRoute: typeof PathlessLayoutSelectOrganizationRoute
  PathlessLayoutTouRoute: typeof PathlessLayoutTouRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutLoginRoute: PathlessLayoutLoginRoute,
  PathlessLayoutPrivacyRoute: PathlessLayoutPrivacyRoute,
  PathlessLayoutRegisterRoute: PathlessLayoutRegisterRoute,
  PathlessLayoutSelectOrganizationRoute: PathlessLayoutSelectOrganizationRoute,
  PathlessLayoutTouRoute: PathlessLayoutTouRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

interface AppAccountRouteRouteChildren {
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteRouteChildren: AppAccountRouteRouteChildren = {
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteRouteWithChildren = AppAccountRouteRoute._addFileChildren(
  AppAccountRouteRouteChildren,
)

interface AppAssetsAssetIdRouteRouteChildren {
  AppAssetsAssetIdEditRoute: typeof AppAssetsAssetIdEditRoute
  AppAssetsAssetIdIndexRoute: typeof AppAssetsAssetIdIndexRoute
}

const AppAssetsAssetIdRouteRouteChildren: AppAssetsAssetIdRouteRouteChildren = {
  AppAssetsAssetIdEditRoute: AppAssetsAssetIdEditRoute,
  AppAssetsAssetIdIndexRoute: AppAssetsAssetIdIndexRoute,
}

const AppAssetsAssetIdRouteRouteWithChildren =
  AppAssetsAssetIdRouteRoute._addFileChildren(
    AppAssetsAssetIdRouteRouteChildren,
  )

interface AppAssetsRouteRouteChildren {
  AppAssetsAssetIdRouteRoute: typeof AppAssetsAssetIdRouteRouteWithChildren
  AppAssetsAddRoute: typeof AppAssetsAddRoute
  AppAssetsPlaygroundRoute: typeof AppAssetsPlaygroundRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
}

const AppAssetsRouteRouteChildren: AppAssetsRouteRouteChildren = {
  AppAssetsAssetIdRouteRoute: AppAssetsAssetIdRouteRouteWithChildren,
  AppAssetsAddRoute: AppAssetsAddRoute,
  AppAssetsPlaygroundRoute: AppAssetsPlaygroundRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
}

const AppAssetsRouteRouteWithChildren = AppAssetsRouteRoute._addFileChildren(
  AppAssetsRouteRouteChildren,
)

interface AppBlocksBlockIdRouteRouteChildren {
  AppBlocksBlockIdEditRoute: typeof AppBlocksBlockIdEditRoute
  AppBlocksBlockIdPointsRoute: typeof AppBlocksBlockIdPointsRoute
  AppBlocksBlockIdIndexRoute: typeof AppBlocksBlockIdIndexRoute
}

const AppBlocksBlockIdRouteRouteChildren: AppBlocksBlockIdRouteRouteChildren = {
  AppBlocksBlockIdEditRoute: AppBlocksBlockIdEditRoute,
  AppBlocksBlockIdPointsRoute: AppBlocksBlockIdPointsRoute,
  AppBlocksBlockIdIndexRoute: AppBlocksBlockIdIndexRoute,
}

const AppBlocksBlockIdRouteRouteWithChildren =
  AppBlocksBlockIdRouteRoute._addFileChildren(
    AppBlocksBlockIdRouteRouteChildren,
  )

interface AppBlocksRouteRouteChildren {
  AppBlocksBlockIdRouteRoute: typeof AppBlocksBlockIdRouteRouteWithChildren
  AppBlocksAddRoute: typeof AppBlocksAddRoute
  AppBlocksIndexRoute: typeof AppBlocksIndexRoute
}

const AppBlocksRouteRouteChildren: AppBlocksRouteRouteChildren = {
  AppBlocksBlockIdRouteRoute: AppBlocksBlockIdRouteRouteWithChildren,
  AppBlocksAddRoute: AppBlocksAddRoute,
  AppBlocksIndexRoute: AppBlocksIndexRoute,
}

const AppBlocksRouteRouteWithChildren = AppBlocksRouteRoute._addFileChildren(
  AppBlocksRouteRouteChildren,
)

interface AppBotsBotIdRouteRouteChildren {
  AppBotsBotIdEditRoute: typeof AppBotsBotIdEditRoute
  AppBotsBotIdIndexRoute: typeof AppBotsBotIdIndexRoute
}

const AppBotsBotIdRouteRouteChildren: AppBotsBotIdRouteRouteChildren = {
  AppBotsBotIdEditRoute: AppBotsBotIdEditRoute,
  AppBotsBotIdIndexRoute: AppBotsBotIdIndexRoute,
}

const AppBotsBotIdRouteRouteWithChildren =
  AppBotsBotIdRouteRoute._addFileChildren(AppBotsBotIdRouteRouteChildren)

interface AppBotsRouteRouteChildren {
  AppBotsBotIdRouteRoute: typeof AppBotsBotIdRouteRouteWithChildren
  AppBotsAddRoute: typeof AppBotsAddRoute
  AppBotsIndexRoute: typeof AppBotsIndexRoute
}

const AppBotsRouteRouteChildren: AppBotsRouteRouteChildren = {
  AppBotsBotIdRouteRoute: AppBotsBotIdRouteRouteWithChildren,
  AppBotsAddRoute: AppBotsAddRoute,
  AppBotsIndexRoute: AppBotsIndexRoute,
}

const AppBotsRouteRouteWithChildren = AppBotsRouteRoute._addFileChildren(
  AppBotsRouteRouteChildren,
)

interface AppChatRouteRouteChildren {
  AppChatSetupRoute: typeof AppChatSetupRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppChatChatIdIndexRoute: typeof AppChatChatIdIndexRoute
}

const AppChatRouteRouteChildren: AppChatRouteRouteChildren = {
  AppChatSetupRoute: AppChatSetupRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppChatChatIdIndexRoute: AppChatChatIdIndexRoute,
}

const AppChatRouteRouteWithChildren = AppChatRouteRoute._addFileChildren(
  AppChatRouteRouteChildren,
)

interface AppCoursesCourseIdRouteRouteChildren {
  AppCoursesCourseIdEditRoute: typeof AppCoursesCourseIdEditRoute
  AppCoursesCourseIdIndexRoute: typeof AppCoursesCourseIdIndexRoute
}

const AppCoursesCourseIdRouteRouteChildren: AppCoursesCourseIdRouteRouteChildren =
  {
    AppCoursesCourseIdEditRoute: AppCoursesCourseIdEditRoute,
    AppCoursesCourseIdIndexRoute: AppCoursesCourseIdIndexRoute,
  }

const AppCoursesCourseIdRouteRouteWithChildren =
  AppCoursesCourseIdRouteRoute._addFileChildren(
    AppCoursesCourseIdRouteRouteChildren,
  )

interface AppCoursesRouteRouteChildren {
  AppCoursesCourseIdRouteRoute: typeof AppCoursesCourseIdRouteRouteWithChildren
  AppCoursesAddRoute: typeof AppCoursesAddRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
}

const AppCoursesRouteRouteChildren: AppCoursesRouteRouteChildren = {
  AppCoursesCourseIdRouteRoute: AppCoursesCourseIdRouteRouteWithChildren,
  AppCoursesAddRoute: AppCoursesAddRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
}

const AppCoursesRouteRouteWithChildren = AppCoursesRouteRoute._addFileChildren(
  AppCoursesRouteRouteChildren,
)

interface AppOrgsOrgIdProvidersProviderSlugRouteRouteChildren {
  AppOrgsOrgIdProvidersProviderSlugEditRoute: typeof AppOrgsOrgIdProvidersProviderSlugEditRoute
  AppOrgsOrgIdProvidersProviderSlugIndexRoute: typeof AppOrgsOrgIdProvidersProviderSlugIndexRoute
}

const AppOrgsOrgIdProvidersProviderSlugRouteRouteChildren: AppOrgsOrgIdProvidersProviderSlugRouteRouteChildren =
  {
    AppOrgsOrgIdProvidersProviderSlugEditRoute:
      AppOrgsOrgIdProvidersProviderSlugEditRoute,
    AppOrgsOrgIdProvidersProviderSlugIndexRoute:
      AppOrgsOrgIdProvidersProviderSlugIndexRoute,
  }

const AppOrgsOrgIdProvidersProviderSlugRouteRouteWithChildren =
  AppOrgsOrgIdProvidersProviderSlugRouteRoute._addFileChildren(
    AppOrgsOrgIdProvidersProviderSlugRouteRouteChildren,
  )

interface AppOrgsOrgIdProvidersRouteRouteChildren {
  AppOrgsOrgIdProvidersProviderSlugRouteRoute: typeof AppOrgsOrgIdProvidersProviderSlugRouteRouteWithChildren
  AppOrgsOrgIdProvidersAddRoute: typeof AppOrgsOrgIdProvidersAddRoute
  AppOrgsOrgIdProvidersIndexRoute: typeof AppOrgsOrgIdProvidersIndexRoute
}

const AppOrgsOrgIdProvidersRouteRouteChildren: AppOrgsOrgIdProvidersRouteRouteChildren =
  {
    AppOrgsOrgIdProvidersProviderSlugRouteRoute:
      AppOrgsOrgIdProvidersProviderSlugRouteRouteWithChildren,
    AppOrgsOrgIdProvidersAddRoute: AppOrgsOrgIdProvidersAddRoute,
    AppOrgsOrgIdProvidersIndexRoute: AppOrgsOrgIdProvidersIndexRoute,
  }

const AppOrgsOrgIdProvidersRouteRouteWithChildren =
  AppOrgsOrgIdProvidersRouteRoute._addFileChildren(
    AppOrgsOrgIdProvidersRouteRouteChildren,
  )

interface AppOrgsOrgIdRouteRouteChildren {
  AppOrgsOrgIdProvidersRouteRoute: typeof AppOrgsOrgIdProvidersRouteRouteWithChildren
  AppOrgsOrgIdEditRoute: typeof AppOrgsOrgIdEditRoute
  AppOrgsOrgIdIndexRoute: typeof AppOrgsOrgIdIndexRoute
}

const AppOrgsOrgIdRouteRouteChildren: AppOrgsOrgIdRouteRouteChildren = {
  AppOrgsOrgIdProvidersRouteRoute: AppOrgsOrgIdProvidersRouteRouteWithChildren,
  AppOrgsOrgIdEditRoute: AppOrgsOrgIdEditRoute,
  AppOrgsOrgIdIndexRoute: AppOrgsOrgIdIndexRoute,
}

const AppOrgsOrgIdRouteRouteWithChildren =
  AppOrgsOrgIdRouteRoute._addFileChildren(AppOrgsOrgIdRouteRouteChildren)

interface AppOrgsRouteRouteChildren {
  AppOrgsOrgIdRouteRoute: typeof AppOrgsOrgIdRouteRouteWithChildren
  AppOrgsAddRoute: typeof AppOrgsAddRoute
  AppOrgsIndexRoute: typeof AppOrgsIndexRoute
}

const AppOrgsRouteRouteChildren: AppOrgsRouteRouteChildren = {
  AppOrgsOrgIdRouteRoute: AppOrgsOrgIdRouteRouteWithChildren,
  AppOrgsAddRoute: AppOrgsAddRoute,
  AppOrgsIndexRoute: AppOrgsIndexRoute,
}

const AppOrgsRouteRouteWithChildren = AppOrgsRouteRoute._addFileChildren(
  AppOrgsRouteRouteChildren,
)

interface AppUsersUserIdRouteRouteChildren {
  AppUsersUserIdEditRoute: typeof AppUsersUserIdEditRoute
}

const AppUsersUserIdRouteRouteChildren: AppUsersUserIdRouteRouteChildren = {
  AppUsersUserIdEditRoute: AppUsersUserIdEditRoute,
}

const AppUsersUserIdRouteRouteWithChildren =
  AppUsersUserIdRouteRoute._addFileChildren(AppUsersUserIdRouteRouteChildren)

interface AppUsersRouteRouteChildren {
  AppUsersUserIdRouteRoute: typeof AppUsersUserIdRouteRouteWithChildren
  AppUsersAddRoute: typeof AppUsersAddRoute
  AppUsersInvitesRoute: typeof AppUsersInvitesRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppUsersRouteRouteChildren: AppUsersRouteRouteChildren = {
  AppUsersUserIdRouteRoute: AppUsersUserIdRouteRouteWithChildren,
  AppUsersAddRoute: AppUsersAddRoute,
  AppUsersInvitesRoute: AppUsersInvitesRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppUsersRouteRouteWithChildren = AppUsersRouteRoute._addFileChildren(
  AppUsersRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAccountRouteRoute: typeof AppAccountRouteRouteWithChildren
  AppAssetsRouteRoute: typeof AppAssetsRouteRouteWithChildren
  AppBlocksRouteRoute: typeof AppBlocksRouteRouteWithChildren
  AppBotsRouteRoute: typeof AppBotsRouteRouteWithChildren
  AppChatRouteRoute: typeof AppChatRouteRouteWithChildren
  AppCoursesRouteRoute: typeof AppCoursesRouteRouteWithChildren
  AppOrgsRouteRoute: typeof AppOrgsRouteRouteWithChildren
  AppUsersRouteRoute: typeof AppUsersRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRouteRoute: AppAccountRouteRouteWithChildren,
  AppAssetsRouteRoute: AppAssetsRouteRouteWithChildren,
  AppBlocksRouteRoute: AppBlocksRouteRouteWithChildren,
  AppBotsRouteRoute: AppBotsRouteRouteWithChildren,
  AppChatRouteRoute: AppChatRouteRouteWithChildren,
  AppCoursesRouteRoute: AppCoursesRouteRouteWithChildren,
  AppOrgsRouteRoute: AppOrgsRouteRouteWithChildren,
  AppUsersRouteRoute: AppUsersRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocSplatRoute: ApiDocSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
