/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PathlessLayoutTouRouteImport } from './routes/_pathlessLayout/tou'
import { Route as PathlessLayoutSelectOrganizationRouteImport } from './routes/_pathlessLayout/select-organization'
import { Route as PathlessLayoutRegisterRouteImport } from './routes/_pathlessLayout/register'
import { Route as PathlessLayoutPrivacyRouteImport } from './routes/_pathlessLayout/privacy'
import { Route as PathlessLayoutLoginRouteImport } from './routes/_pathlessLayout/login'
import { Route as AppAccountIndexRouteImport } from './routes/app/account/index'
import { Route as AppusersUsersIndexRouteImport } from './routes/app/(users)/users.index'
import { Route as ApporgsOrgsIndexRouteImport } from './routes/app/(orgs)/orgs.index'
import { Route as AppcoursesCoursesIndexRouteImport } from './routes/app/(courses)/courses.index'
import { Route as AppchatChatIndexRouteImport } from './routes/app/(chat)/chat.index'
import { Route as AppbotsBotsIndexRouteImport } from './routes/app/(bots)/bots.index'
import { Route as AppblocksBlocksIndexRouteImport } from './routes/app/(blocks)/blocks.index'
import { Route as AppassetsAssetsIndexRouteImport } from './routes/app/(assets)/assets.index'
import { Route as AppusersUsersInvitesRouteImport } from './routes/app/(users)/users.invites'
import { Route as AppusersUsersAddRouteImport } from './routes/app/(users)/users.add'
import { Route as ApporgsOrgsAddRouteImport } from './routes/app/(orgs)/orgs.add'
import { Route as ApporgsOrgsOrgIdRouteImport } from './routes/app/(orgs)/orgs.$orgId'
import { Route as AppcoursesCoursesAddRouteImport } from './routes/app/(courses)/courses.add'
import { Route as AppcoursesCoursesCourseIdRouteImport } from './routes/app/(courses)/courses.$courseId'
import { Route as AppchatChatChatIdRouteImport } from './routes/app/(chat)/chat.$chatId'
import { Route as AppbotsBotsAddRouteImport } from './routes/app/(bots)/bots.add'
import { Route as AppbotsBotsBotIdRouteImport } from './routes/app/(bots)/bots.$botId'
import { Route as AppblocksBlocksAddRouteImport } from './routes/app/(blocks)/blocks.add'
import { Route as AppblocksBlocksBlockIdRouteImport } from './routes/app/(blocks)/blocks.$blockId'
import { Route as AppassetsAssetsPlaygroundRouteImport } from './routes/app/(assets)/assets.playground'
import { Route as AppassetsAssetsAddRouteImport } from './routes/app/(assets)/assets.add'
import { Route as AppassetsAssetsAssetIdRouteImport } from './routes/app/(assets)/assets.$assetId'
import { Route as AppusersUsersUserIdEditRouteImport } from './routes/app/(users)/users_.$userId.edit'
import { Route as ApporgsOrgsOrgIdEditRouteImport } from './routes/app/(orgs)/orgs_.$orgId.edit'
import { Route as AppcoursesCoursesCourseIdEditRouteImport } from './routes/app/(courses)/courses_.$courseId.edit'
import { Route as AppbotsBotsBotIdEditRouteImport } from './routes/app/(bots)/bots_.$botId.edit'
import { Route as AppblocksBlocksBlockIdEditRouteImport } from './routes/app/(blocks)/blocks_.$blockId.edit'
import { Route as AppassetsAssetsAssetIdEditRouteImport } from './routes/app/(assets)/assets_.$assetId.edit'
import { Route as AppassetsAssetsAssetIdChunksRouteImport } from './routes/app/(assets)/assets_.$assetId.chunks'
import { Route as ApporgsOrgsOrgIdProvidersIndexRouteImport } from './routes/app/(orgs)/orgs.$orgId_.providers.index'
import { Route as ApporgsOrgsOrgIdProvidersAddRouteImport } from './routes/app/(orgs)/orgs.$orgId_.providers.add'
import { Route as ApporgsOrgsOrgIdProvidersProviderSlugRouteImport } from './routes/app/(orgs)/orgs.$orgId_.providers.$providerSlug'
import { Route as ApporgsOrgsOrgIdProvidersProviderSlugEditRouteImport } from './routes/app/(orgs)/orgs.$orgId_.providers_.$providerSlug.edit'
import { ServerRoute as ApiRpcSplatServerRouteImport } from './routes/api/rpc/$'
import { ServerRoute as ApiDocSplatServerRouteImport } from './routes/api/doc/$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PathlessLayoutTouRoute = PathlessLayoutTouRouteImport.update({
  id: '/tou',
  path: '/tou',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutSelectOrganizationRoute =
  PathlessLayoutSelectOrganizationRouteImport.update({
    id: '/select-organization',
    path: '/select-organization',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutRegisterRoute = PathlessLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutPrivacyRoute = PathlessLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutLoginRoute = PathlessLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppusersUsersIndexRoute = AppusersUsersIndexRouteImport.update({
  id: '/(users)/users/',
  path: '/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApporgsOrgsIndexRoute = ApporgsOrgsIndexRouteImport.update({
  id: '/(orgs)/orgs/',
  path: '/orgs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppcoursesCoursesIndexRoute = AppcoursesCoursesIndexRouteImport.update({
  id: '/(courses)/courses/',
  path: '/courses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppchatChatIndexRoute = AppchatChatIndexRouteImport.update({
  id: '/(chat)/chat/',
  path: '/chat/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppbotsBotsIndexRoute = AppbotsBotsIndexRouteImport.update({
  id: '/(bots)/bots/',
  path: '/bots/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppblocksBlocksIndexRoute = AppblocksBlocksIndexRouteImport.update({
  id: '/(blocks)/blocks/',
  path: '/blocks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppassetsAssetsIndexRoute = AppassetsAssetsIndexRouteImport.update({
  id: '/(assets)/assets/',
  path: '/assets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppusersUsersInvitesRoute = AppusersUsersInvitesRouteImport.update({
  id: '/(users)/users/invites',
  path: '/users/invites',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppusersUsersAddRoute = AppusersUsersAddRouteImport.update({
  id: '/(users)/users/add',
  path: '/users/add',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApporgsOrgsAddRoute = ApporgsOrgsAddRouteImport.update({
  id: '/(orgs)/orgs/add',
  path: '/orgs/add',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApporgsOrgsOrgIdRoute = ApporgsOrgsOrgIdRouteImport.update({
  id: '/(orgs)/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppcoursesCoursesAddRoute = AppcoursesCoursesAddRouteImport.update({
  id: '/(courses)/courses/add',
  path: '/courses/add',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppcoursesCoursesCourseIdRoute =
  AppcoursesCoursesCourseIdRouteImport.update({
    id: '/(courses)/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppchatChatChatIdRoute = AppchatChatChatIdRouteImport.update({
  id: '/(chat)/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppbotsBotsAddRoute = AppbotsBotsAddRouteImport.update({
  id: '/(bots)/bots/add',
  path: '/bots/add',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppbotsBotsBotIdRoute = AppbotsBotsBotIdRouteImport.update({
  id: '/(bots)/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppblocksBlocksAddRoute = AppblocksBlocksAddRouteImport.update({
  id: '/(blocks)/blocks/add',
  path: '/blocks/add',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppblocksBlocksBlockIdRoute = AppblocksBlocksBlockIdRouteImport.update({
  id: '/(blocks)/blocks/$blockId',
  path: '/blocks/$blockId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppassetsAssetsPlaygroundRoute =
  AppassetsAssetsPlaygroundRouteImport.update({
    id: '/(assets)/assets/playground',
    path: '/assets/playground',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppassetsAssetsAddRoute = AppassetsAssetsAddRouteImport.update({
  id: '/(assets)/assets/add',
  path: '/assets/add',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppassetsAssetsAssetIdRoute = AppassetsAssetsAssetIdRouteImport.update({
  id: '/(assets)/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppusersUsersUserIdEditRoute = AppusersUsersUserIdEditRouteImport.update({
  id: '/(users)/users_/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApporgsOrgsOrgIdEditRoute = ApporgsOrgsOrgIdEditRouteImport.update({
  id: '/(orgs)/orgs_/$orgId/edit',
  path: '/orgs/$orgId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppcoursesCoursesCourseIdEditRoute =
  AppcoursesCoursesCourseIdEditRouteImport.update({
    id: '/(courses)/courses_/$courseId/edit',
    path: '/courses/$courseId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppbotsBotsBotIdEditRoute = AppbotsBotsBotIdEditRouteImport.update({
  id: '/(bots)/bots_/$botId/edit',
  path: '/bots/$botId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppblocksBlocksBlockIdEditRoute =
  AppblocksBlocksBlockIdEditRouteImport.update({
    id: '/(blocks)/blocks_/$blockId/edit',
    path: '/blocks/$blockId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppassetsAssetsAssetIdEditRoute =
  AppassetsAssetsAssetIdEditRouteImport.update({
    id: '/(assets)/assets_/$assetId/edit',
    path: '/assets/$assetId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppassetsAssetsAssetIdChunksRoute =
  AppassetsAssetsAssetIdChunksRouteImport.update({
    id: '/(assets)/assets_/$assetId/chunks',
    path: '/assets/$assetId/chunks',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApporgsOrgsOrgIdProvidersIndexRoute =
  ApporgsOrgsOrgIdProvidersIndexRouteImport.update({
    id: '/(orgs)/orgs/$orgId_/providers/',
    path: '/orgs/$orgId/providers/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApporgsOrgsOrgIdProvidersAddRoute =
  ApporgsOrgsOrgIdProvidersAddRouteImport.update({
    id: '/(orgs)/orgs/$orgId_/providers/add',
    path: '/orgs/$orgId/providers/add',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApporgsOrgsOrgIdProvidersProviderSlugRoute =
  ApporgsOrgsOrgIdProvidersProviderSlugRouteImport.update({
    id: '/(orgs)/orgs/$orgId_/providers/$providerSlug',
    path: '/orgs/$orgId/providers/$providerSlug',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApporgsOrgsOrgIdProvidersProviderSlugEditRoute =
  ApporgsOrgsOrgIdProvidersProviderSlugEditRouteImport.update({
    id: '/(orgs)/orgs/$orgId_/providers_/$providerSlug/edit',
    path: '/orgs/$orgId/providers/$providerSlug/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiRpcSplatServerRoute = ApiRpcSplatServerRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiDocSplatServerRoute = ApiDocSplatServerRouteImport.update({
  id: '/api/doc/$',
  path: '/api/doc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof PathlessLayoutLoginRoute
  '/privacy': typeof PathlessLayoutPrivacyRoute
  '/register': typeof PathlessLayoutRegisterRoute
  '/select-organization': typeof PathlessLayoutSelectOrganizationRoute
  '/tou': typeof PathlessLayoutTouRoute
  '/app/': typeof AppIndexRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/assets/$assetId': typeof AppassetsAssetsAssetIdRoute
  '/app/assets/add': typeof AppassetsAssetsAddRoute
  '/app/assets/playground': typeof AppassetsAssetsPlaygroundRoute
  '/app/blocks/$blockId': typeof AppblocksBlocksBlockIdRoute
  '/app/blocks/add': typeof AppblocksBlocksAddRoute
  '/app/bots/$botId': typeof AppbotsBotsBotIdRoute
  '/app/bots/add': typeof AppbotsBotsAddRoute
  '/app/chat/$chatId': typeof AppchatChatChatIdRoute
  '/app/courses/$courseId': typeof AppcoursesCoursesCourseIdRoute
  '/app/courses/add': typeof AppcoursesCoursesAddRoute
  '/app/orgs/$orgId': typeof ApporgsOrgsOrgIdRoute
  '/app/orgs/add': typeof ApporgsOrgsAddRoute
  '/app/users/add': typeof AppusersUsersAddRoute
  '/app/users/invites': typeof AppusersUsersInvitesRoute
  '/app/assets': typeof AppassetsAssetsIndexRoute
  '/app/blocks': typeof AppblocksBlocksIndexRoute
  '/app/bots': typeof AppbotsBotsIndexRoute
  '/app/chat': typeof AppchatChatIndexRoute
  '/app/courses': typeof AppcoursesCoursesIndexRoute
  '/app/orgs': typeof ApporgsOrgsIndexRoute
  '/app/users': typeof AppusersUsersIndexRoute
  '/app/assets/$assetId/chunks': typeof AppassetsAssetsAssetIdChunksRoute
  '/app/assets/$assetId/edit': typeof AppassetsAssetsAssetIdEditRoute
  '/app/blocks/$blockId/edit': typeof AppblocksBlocksBlockIdEditRoute
  '/app/bots/$botId/edit': typeof AppbotsBotsBotIdEditRoute
  '/app/courses/$courseId/edit': typeof AppcoursesCoursesCourseIdEditRoute
  '/app/orgs/$orgId/edit': typeof ApporgsOrgsOrgIdEditRoute
  '/app/users/$userId/edit': typeof AppusersUsersUserIdEditRoute
  '/app/orgs/$orgId/providers/$providerSlug': typeof ApporgsOrgsOrgIdProvidersProviderSlugRoute
  '/app/orgs/$orgId/providers/add': typeof ApporgsOrgsOrgIdProvidersAddRoute
  '/app/orgs/$orgId/providers': typeof ApporgsOrgsOrgIdProvidersIndexRoute
  '/app/orgs/$orgId/providers/$providerSlug/edit': typeof ApporgsOrgsOrgIdProvidersProviderSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PathlessLayoutLoginRoute
  '/privacy': typeof PathlessLayoutPrivacyRoute
  '/register': typeof PathlessLayoutRegisterRoute
  '/select-organization': typeof PathlessLayoutSelectOrganizationRoute
  '/tou': typeof PathlessLayoutTouRoute
  '/app': typeof AppIndexRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/assets/$assetId': typeof AppassetsAssetsAssetIdRoute
  '/app/assets/add': typeof AppassetsAssetsAddRoute
  '/app/assets/playground': typeof AppassetsAssetsPlaygroundRoute
  '/app/blocks/$blockId': typeof AppblocksBlocksBlockIdRoute
  '/app/blocks/add': typeof AppblocksBlocksAddRoute
  '/app/bots/$botId': typeof AppbotsBotsBotIdRoute
  '/app/bots/add': typeof AppbotsBotsAddRoute
  '/app/chat/$chatId': typeof AppchatChatChatIdRoute
  '/app/courses/$courseId': typeof AppcoursesCoursesCourseIdRoute
  '/app/courses/add': typeof AppcoursesCoursesAddRoute
  '/app/orgs/$orgId': typeof ApporgsOrgsOrgIdRoute
  '/app/orgs/add': typeof ApporgsOrgsAddRoute
  '/app/users/add': typeof AppusersUsersAddRoute
  '/app/users/invites': typeof AppusersUsersInvitesRoute
  '/app/assets': typeof AppassetsAssetsIndexRoute
  '/app/blocks': typeof AppblocksBlocksIndexRoute
  '/app/bots': typeof AppbotsBotsIndexRoute
  '/app/chat': typeof AppchatChatIndexRoute
  '/app/courses': typeof AppcoursesCoursesIndexRoute
  '/app/orgs': typeof ApporgsOrgsIndexRoute
  '/app/users': typeof AppusersUsersIndexRoute
  '/app/assets/$assetId/chunks': typeof AppassetsAssetsAssetIdChunksRoute
  '/app/assets/$assetId/edit': typeof AppassetsAssetsAssetIdEditRoute
  '/app/blocks/$blockId/edit': typeof AppblocksBlocksBlockIdEditRoute
  '/app/bots/$botId/edit': typeof AppbotsBotsBotIdEditRoute
  '/app/courses/$courseId/edit': typeof AppcoursesCoursesCourseIdEditRoute
  '/app/orgs/$orgId/edit': typeof ApporgsOrgsOrgIdEditRoute
  '/app/users/$userId/edit': typeof AppusersUsersUserIdEditRoute
  '/app/orgs/$orgId/providers/$providerSlug': typeof ApporgsOrgsOrgIdProvidersProviderSlugRoute
  '/app/orgs/$orgId/providers/add': typeof ApporgsOrgsOrgIdProvidersAddRoute
  '/app/orgs/$orgId/providers': typeof ApporgsOrgsOrgIdProvidersIndexRoute
  '/app/orgs/$orgId/providers/$providerSlug/edit': typeof ApporgsOrgsOrgIdProvidersProviderSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/_pathlessLayout/login': typeof PathlessLayoutLoginRoute
  '/_pathlessLayout/privacy': typeof PathlessLayoutPrivacyRoute
  '/_pathlessLayout/register': typeof PathlessLayoutRegisterRoute
  '/_pathlessLayout/select-organization': typeof PathlessLayoutSelectOrganizationRoute
  '/_pathlessLayout/tou': typeof PathlessLayoutTouRoute
  '/app/': typeof AppIndexRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/(assets)/assets/$assetId': typeof AppassetsAssetsAssetIdRoute
  '/app/(assets)/assets/add': typeof AppassetsAssetsAddRoute
  '/app/(assets)/assets/playground': typeof AppassetsAssetsPlaygroundRoute
  '/app/(blocks)/blocks/$blockId': typeof AppblocksBlocksBlockIdRoute
  '/app/(blocks)/blocks/add': typeof AppblocksBlocksAddRoute
  '/app/(bots)/bots/$botId': typeof AppbotsBotsBotIdRoute
  '/app/(bots)/bots/add': typeof AppbotsBotsAddRoute
  '/app/(chat)/chat/$chatId': typeof AppchatChatChatIdRoute
  '/app/(courses)/courses/$courseId': typeof AppcoursesCoursesCourseIdRoute
  '/app/(courses)/courses/add': typeof AppcoursesCoursesAddRoute
  '/app/(orgs)/orgs/$orgId': typeof ApporgsOrgsOrgIdRoute
  '/app/(orgs)/orgs/add': typeof ApporgsOrgsAddRoute
  '/app/(users)/users/add': typeof AppusersUsersAddRoute
  '/app/(users)/users/invites': typeof AppusersUsersInvitesRoute
  '/app/(assets)/assets/': typeof AppassetsAssetsIndexRoute
  '/app/(blocks)/blocks/': typeof AppblocksBlocksIndexRoute
  '/app/(bots)/bots/': typeof AppbotsBotsIndexRoute
  '/app/(chat)/chat/': typeof AppchatChatIndexRoute
  '/app/(courses)/courses/': typeof AppcoursesCoursesIndexRoute
  '/app/(orgs)/orgs/': typeof ApporgsOrgsIndexRoute
  '/app/(users)/users/': typeof AppusersUsersIndexRoute
  '/app/(assets)/assets_/$assetId/chunks': typeof AppassetsAssetsAssetIdChunksRoute
  '/app/(assets)/assets_/$assetId/edit': typeof AppassetsAssetsAssetIdEditRoute
  '/app/(blocks)/blocks_/$blockId/edit': typeof AppblocksBlocksBlockIdEditRoute
  '/app/(bots)/bots_/$botId/edit': typeof AppbotsBotsBotIdEditRoute
  '/app/(courses)/courses_/$courseId/edit': typeof AppcoursesCoursesCourseIdEditRoute
  '/app/(orgs)/orgs_/$orgId/edit': typeof ApporgsOrgsOrgIdEditRoute
  '/app/(users)/users_/$userId/edit': typeof AppusersUsersUserIdEditRoute
  '/app/(orgs)/orgs/$orgId_/providers/$providerSlug': typeof ApporgsOrgsOrgIdProvidersProviderSlugRoute
  '/app/(orgs)/orgs/$orgId_/providers/add': typeof ApporgsOrgsOrgIdProvidersAddRoute
  '/app/(orgs)/orgs/$orgId_/providers/': typeof ApporgsOrgsOrgIdProvidersIndexRoute
  '/app/(orgs)/orgs/$orgId_/providers_/$providerSlug/edit': typeof ApporgsOrgsOrgIdProvidersProviderSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/privacy'
    | '/register'
    | '/select-organization'
    | '/tou'
    | '/app/'
    | '/app/account'
    | '/app/assets/$assetId'
    | '/app/assets/add'
    | '/app/assets/playground'
    | '/app/blocks/$blockId'
    | '/app/blocks/add'
    | '/app/bots/$botId'
    | '/app/bots/add'
    | '/app/chat/$chatId'
    | '/app/courses/$courseId'
    | '/app/courses/add'
    | '/app/orgs/$orgId'
    | '/app/orgs/add'
    | '/app/users/add'
    | '/app/users/invites'
    | '/app/assets'
    | '/app/blocks'
    | '/app/bots'
    | '/app/chat'
    | '/app/courses'
    | '/app/orgs'
    | '/app/users'
    | '/app/assets/$assetId/chunks'
    | '/app/assets/$assetId/edit'
    | '/app/blocks/$blockId/edit'
    | '/app/bots/$botId/edit'
    | '/app/courses/$courseId/edit'
    | '/app/orgs/$orgId/edit'
    | '/app/users/$userId/edit'
    | '/app/orgs/$orgId/providers/$providerSlug'
    | '/app/orgs/$orgId/providers/add'
    | '/app/orgs/$orgId/providers'
    | '/app/orgs/$orgId/providers/$providerSlug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/register'
    | '/select-organization'
    | '/tou'
    | '/app'
    | '/app/account'
    | '/app/assets/$assetId'
    | '/app/assets/add'
    | '/app/assets/playground'
    | '/app/blocks/$blockId'
    | '/app/blocks/add'
    | '/app/bots/$botId'
    | '/app/bots/add'
    | '/app/chat/$chatId'
    | '/app/courses/$courseId'
    | '/app/courses/add'
    | '/app/orgs/$orgId'
    | '/app/orgs/add'
    | '/app/users/add'
    | '/app/users/invites'
    | '/app/assets'
    | '/app/blocks'
    | '/app/bots'
    | '/app/chat'
    | '/app/courses'
    | '/app/orgs'
    | '/app/users'
    | '/app/assets/$assetId/chunks'
    | '/app/assets/$assetId/edit'
    | '/app/blocks/$blockId/edit'
    | '/app/bots/$botId/edit'
    | '/app/courses/$courseId/edit'
    | '/app/orgs/$orgId/edit'
    | '/app/users/$userId/edit'
    | '/app/orgs/$orgId/providers/$providerSlug'
    | '/app/orgs/$orgId/providers/add'
    | '/app/orgs/$orgId/providers'
    | '/app/orgs/$orgId/providers/$providerSlug/edit'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/app'
    | '/_pathlessLayout/login'
    | '/_pathlessLayout/privacy'
    | '/_pathlessLayout/register'
    | '/_pathlessLayout/select-organization'
    | '/_pathlessLayout/tou'
    | '/app/'
    | '/app/account/'
    | '/app/(assets)/assets/$assetId'
    | '/app/(assets)/assets/add'
    | '/app/(assets)/assets/playground'
    | '/app/(blocks)/blocks/$blockId'
    | '/app/(blocks)/blocks/add'
    | '/app/(bots)/bots/$botId'
    | '/app/(bots)/bots/add'
    | '/app/(chat)/chat/$chatId'
    | '/app/(courses)/courses/$courseId'
    | '/app/(courses)/courses/add'
    | '/app/(orgs)/orgs/$orgId'
    | '/app/(orgs)/orgs/add'
    | '/app/(users)/users/add'
    | '/app/(users)/users/invites'
    | '/app/(assets)/assets/'
    | '/app/(blocks)/blocks/'
    | '/app/(bots)/bots/'
    | '/app/(chat)/chat/'
    | '/app/(courses)/courses/'
    | '/app/(orgs)/orgs/'
    | '/app/(users)/users/'
    | '/app/(assets)/assets_/$assetId/chunks'
    | '/app/(assets)/assets_/$assetId/edit'
    | '/app/(blocks)/blocks_/$blockId/edit'
    | '/app/(bots)/bots_/$botId/edit'
    | '/app/(courses)/courses_/$courseId/edit'
    | '/app/(orgs)/orgs_/$orgId/edit'
    | '/app/(users)/users_/$userId/edit'
    | '/app/(orgs)/orgs/$orgId_/providers/$providerSlug'
    | '/app/(orgs)/orgs/$orgId_/providers/add'
    | '/app/(orgs)/orgs/$orgId_/providers/'
    | '/app/(orgs)/orgs/$orgId_/providers_/$providerSlug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/doc/$': typeof ApiDocSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/doc/$': typeof ApiDocSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/doc/$': typeof ApiDocSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/doc/$' | '/api/rpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/doc/$' | '/api/rpc/$'
  id: '__root__' | '/api/auth/$' | '/api/doc/$' | '/api/rpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiDocSplatServerRoute: typeof ApiDocSplatServerRoute
  ApiRpcSplatServerRoute: typeof ApiRpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_pathlessLayout/tou': {
      id: '/_pathlessLayout/tou'
      path: '/tou'
      fullPath: '/tou'
      preLoaderRoute: typeof PathlessLayoutTouRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/select-organization': {
      id: '/_pathlessLayout/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof PathlessLayoutSelectOrganizationRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/register': {
      id: '/_pathlessLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PathlessLayoutRegisterRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/privacy': {
      id: '/_pathlessLayout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PathlessLayoutPrivacyRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/login': {
      id: '/_pathlessLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PathlessLayoutLoginRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(users)/users/': {
      id: '/app/(users)/users/'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppusersUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(orgs)/orgs/': {
      id: '/app/(orgs)/orgs/'
      path: '/orgs'
      fullPath: '/app/orgs'
      preLoaderRoute: typeof ApporgsOrgsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(courses)/courses/': {
      id: '/app/(courses)/courses/'
      path: '/courses'
      fullPath: '/app/courses'
      preLoaderRoute: typeof AppcoursesCoursesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(chat)/chat/': {
      id: '/app/(chat)/chat/'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppchatChatIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(bots)/bots/': {
      id: '/app/(bots)/bots/'
      path: '/bots'
      fullPath: '/app/bots'
      preLoaderRoute: typeof AppbotsBotsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(blocks)/blocks/': {
      id: '/app/(blocks)/blocks/'
      path: '/blocks'
      fullPath: '/app/blocks'
      preLoaderRoute: typeof AppblocksBlocksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(assets)/assets/': {
      id: '/app/(assets)/assets/'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppassetsAssetsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(users)/users/invites': {
      id: '/app/(users)/users/invites'
      path: '/users/invites'
      fullPath: '/app/users/invites'
      preLoaderRoute: typeof AppusersUsersInvitesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(users)/users/add': {
      id: '/app/(users)/users/add'
      path: '/users/add'
      fullPath: '/app/users/add'
      preLoaderRoute: typeof AppusersUsersAddRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(orgs)/orgs/add': {
      id: '/app/(orgs)/orgs/add'
      path: '/orgs/add'
      fullPath: '/app/orgs/add'
      preLoaderRoute: typeof ApporgsOrgsAddRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(orgs)/orgs/$orgId': {
      id: '/app/(orgs)/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/app/orgs/$orgId'
      preLoaderRoute: typeof ApporgsOrgsOrgIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(courses)/courses/add': {
      id: '/app/(courses)/courses/add'
      path: '/courses/add'
      fullPath: '/app/courses/add'
      preLoaderRoute: typeof AppcoursesCoursesAddRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(courses)/courses/$courseId': {
      id: '/app/(courses)/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/app/courses/$courseId'
      preLoaderRoute: typeof AppcoursesCoursesCourseIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(chat)/chat/$chatId': {
      id: '/app/(chat)/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/app/chat/$chatId'
      preLoaderRoute: typeof AppchatChatChatIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(bots)/bots/add': {
      id: '/app/(bots)/bots/add'
      path: '/bots/add'
      fullPath: '/app/bots/add'
      preLoaderRoute: typeof AppbotsBotsAddRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(bots)/bots/$botId': {
      id: '/app/(bots)/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/app/bots/$botId'
      preLoaderRoute: typeof AppbotsBotsBotIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(blocks)/blocks/add': {
      id: '/app/(blocks)/blocks/add'
      path: '/blocks/add'
      fullPath: '/app/blocks/add'
      preLoaderRoute: typeof AppblocksBlocksAddRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(blocks)/blocks/$blockId': {
      id: '/app/(blocks)/blocks/$blockId'
      path: '/blocks/$blockId'
      fullPath: '/app/blocks/$blockId'
      preLoaderRoute: typeof AppblocksBlocksBlockIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(assets)/assets/playground': {
      id: '/app/(assets)/assets/playground'
      path: '/assets/playground'
      fullPath: '/app/assets/playground'
      preLoaderRoute: typeof AppassetsAssetsPlaygroundRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(assets)/assets/add': {
      id: '/app/(assets)/assets/add'
      path: '/assets/add'
      fullPath: '/app/assets/add'
      preLoaderRoute: typeof AppassetsAssetsAddRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(assets)/assets/$assetId': {
      id: '/app/(assets)/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/app/assets/$assetId'
      preLoaderRoute: typeof AppassetsAssetsAssetIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(users)/users_/$userId/edit': {
      id: '/app/(users)/users_/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/app/users/$userId/edit'
      preLoaderRoute: typeof AppusersUsersUserIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(orgs)/orgs_/$orgId/edit': {
      id: '/app/(orgs)/orgs_/$orgId/edit'
      path: '/orgs/$orgId/edit'
      fullPath: '/app/orgs/$orgId/edit'
      preLoaderRoute: typeof ApporgsOrgsOrgIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(courses)/courses_/$courseId/edit': {
      id: '/app/(courses)/courses_/$courseId/edit'
      path: '/courses/$courseId/edit'
      fullPath: '/app/courses/$courseId/edit'
      preLoaderRoute: typeof AppcoursesCoursesCourseIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(bots)/bots_/$botId/edit': {
      id: '/app/(bots)/bots_/$botId/edit'
      path: '/bots/$botId/edit'
      fullPath: '/app/bots/$botId/edit'
      preLoaderRoute: typeof AppbotsBotsBotIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(blocks)/blocks_/$blockId/edit': {
      id: '/app/(blocks)/blocks_/$blockId/edit'
      path: '/blocks/$blockId/edit'
      fullPath: '/app/blocks/$blockId/edit'
      preLoaderRoute: typeof AppblocksBlocksBlockIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(assets)/assets_/$assetId/edit': {
      id: '/app/(assets)/assets_/$assetId/edit'
      path: '/assets/$assetId/edit'
      fullPath: '/app/assets/$assetId/edit'
      preLoaderRoute: typeof AppassetsAssetsAssetIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(assets)/assets_/$assetId/chunks': {
      id: '/app/(assets)/assets_/$assetId/chunks'
      path: '/assets/$assetId/chunks'
      fullPath: '/app/assets/$assetId/chunks'
      preLoaderRoute: typeof AppassetsAssetsAssetIdChunksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(orgs)/orgs/$orgId_/providers/': {
      id: '/app/(orgs)/orgs/$orgId_/providers/'
      path: '/orgs/$orgId/providers'
      fullPath: '/app/orgs/$orgId/providers'
      preLoaderRoute: typeof ApporgsOrgsOrgIdProvidersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(orgs)/orgs/$orgId_/providers/add': {
      id: '/app/(orgs)/orgs/$orgId_/providers/add'
      path: '/orgs/$orgId/providers/add'
      fullPath: '/app/orgs/$orgId/providers/add'
      preLoaderRoute: typeof ApporgsOrgsOrgIdProvidersAddRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(orgs)/orgs/$orgId_/providers/$providerSlug': {
      id: '/app/(orgs)/orgs/$orgId_/providers/$providerSlug'
      path: '/orgs/$orgId/providers/$providerSlug'
      fullPath: '/app/orgs/$orgId/providers/$providerSlug'
      preLoaderRoute: typeof ApporgsOrgsOrgIdProvidersProviderSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(orgs)/orgs/$orgId_/providers_/$providerSlug/edit': {
      id: '/app/(orgs)/orgs/$orgId_/providers_/$providerSlug/edit'
      path: '/orgs/$orgId/providers/$providerSlug/edit'
      fullPath: '/app/orgs/$orgId/providers/$providerSlug/edit'
      preLoaderRoute: typeof ApporgsOrgsOrgIdProvidersProviderSlugEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/doc/$': {
      id: '/api/doc/$'
      path: '/api/doc/$'
      fullPath: '/api/doc/$'
      preLoaderRoute: typeof ApiDocSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutLoginRoute: typeof PathlessLayoutLoginRoute
  PathlessLayoutPrivacyRoute: typeof PathlessLayoutPrivacyRoute
  PathlessLayoutRegisterRoute: typeof PathlessLayoutRegisterRoute
  PathlessLayoutSelectOrganizationRoute: typeof PathlessLayoutSelectOrganizationRoute
  PathlessLayoutTouRoute: typeof PathlessLayoutTouRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutLoginRoute: PathlessLayoutLoginRoute,
  PathlessLayoutPrivacyRoute: PathlessLayoutPrivacyRoute,
  PathlessLayoutRegisterRoute: PathlessLayoutRegisterRoute,
  PathlessLayoutSelectOrganizationRoute: PathlessLayoutSelectOrganizationRoute,
  PathlessLayoutTouRoute: PathlessLayoutTouRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppassetsAssetsAssetIdRoute: typeof AppassetsAssetsAssetIdRoute
  AppassetsAssetsAddRoute: typeof AppassetsAssetsAddRoute
  AppassetsAssetsPlaygroundRoute: typeof AppassetsAssetsPlaygroundRoute
  AppblocksBlocksBlockIdRoute: typeof AppblocksBlocksBlockIdRoute
  AppblocksBlocksAddRoute: typeof AppblocksBlocksAddRoute
  AppbotsBotsBotIdRoute: typeof AppbotsBotsBotIdRoute
  AppbotsBotsAddRoute: typeof AppbotsBotsAddRoute
  AppchatChatChatIdRoute: typeof AppchatChatChatIdRoute
  AppcoursesCoursesCourseIdRoute: typeof AppcoursesCoursesCourseIdRoute
  AppcoursesCoursesAddRoute: typeof AppcoursesCoursesAddRoute
  ApporgsOrgsOrgIdRoute: typeof ApporgsOrgsOrgIdRoute
  ApporgsOrgsAddRoute: typeof ApporgsOrgsAddRoute
  AppusersUsersAddRoute: typeof AppusersUsersAddRoute
  AppusersUsersInvitesRoute: typeof AppusersUsersInvitesRoute
  AppassetsAssetsIndexRoute: typeof AppassetsAssetsIndexRoute
  AppblocksBlocksIndexRoute: typeof AppblocksBlocksIndexRoute
  AppbotsBotsIndexRoute: typeof AppbotsBotsIndexRoute
  AppchatChatIndexRoute: typeof AppchatChatIndexRoute
  AppcoursesCoursesIndexRoute: typeof AppcoursesCoursesIndexRoute
  ApporgsOrgsIndexRoute: typeof ApporgsOrgsIndexRoute
  AppusersUsersIndexRoute: typeof AppusersUsersIndexRoute
  AppassetsAssetsAssetIdChunksRoute: typeof AppassetsAssetsAssetIdChunksRoute
  AppassetsAssetsAssetIdEditRoute: typeof AppassetsAssetsAssetIdEditRoute
  AppblocksBlocksBlockIdEditRoute: typeof AppblocksBlocksBlockIdEditRoute
  AppbotsBotsBotIdEditRoute: typeof AppbotsBotsBotIdEditRoute
  AppcoursesCoursesCourseIdEditRoute: typeof AppcoursesCoursesCourseIdEditRoute
  ApporgsOrgsOrgIdEditRoute: typeof ApporgsOrgsOrgIdEditRoute
  AppusersUsersUserIdEditRoute: typeof AppusersUsersUserIdEditRoute
  ApporgsOrgsOrgIdProvidersProviderSlugRoute: typeof ApporgsOrgsOrgIdProvidersProviderSlugRoute
  ApporgsOrgsOrgIdProvidersAddRoute: typeof ApporgsOrgsOrgIdProvidersAddRoute
  ApporgsOrgsOrgIdProvidersIndexRoute: typeof ApporgsOrgsOrgIdProvidersIndexRoute
  ApporgsOrgsOrgIdProvidersProviderSlugEditRoute: typeof ApporgsOrgsOrgIdProvidersProviderSlugEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppassetsAssetsAssetIdRoute: AppassetsAssetsAssetIdRoute,
  AppassetsAssetsAddRoute: AppassetsAssetsAddRoute,
  AppassetsAssetsPlaygroundRoute: AppassetsAssetsPlaygroundRoute,
  AppblocksBlocksBlockIdRoute: AppblocksBlocksBlockIdRoute,
  AppblocksBlocksAddRoute: AppblocksBlocksAddRoute,
  AppbotsBotsBotIdRoute: AppbotsBotsBotIdRoute,
  AppbotsBotsAddRoute: AppbotsBotsAddRoute,
  AppchatChatChatIdRoute: AppchatChatChatIdRoute,
  AppcoursesCoursesCourseIdRoute: AppcoursesCoursesCourseIdRoute,
  AppcoursesCoursesAddRoute: AppcoursesCoursesAddRoute,
  ApporgsOrgsOrgIdRoute: ApporgsOrgsOrgIdRoute,
  ApporgsOrgsAddRoute: ApporgsOrgsAddRoute,
  AppusersUsersAddRoute: AppusersUsersAddRoute,
  AppusersUsersInvitesRoute: AppusersUsersInvitesRoute,
  AppassetsAssetsIndexRoute: AppassetsAssetsIndexRoute,
  AppblocksBlocksIndexRoute: AppblocksBlocksIndexRoute,
  AppbotsBotsIndexRoute: AppbotsBotsIndexRoute,
  AppchatChatIndexRoute: AppchatChatIndexRoute,
  AppcoursesCoursesIndexRoute: AppcoursesCoursesIndexRoute,
  ApporgsOrgsIndexRoute: ApporgsOrgsIndexRoute,
  AppusersUsersIndexRoute: AppusersUsersIndexRoute,
  AppassetsAssetsAssetIdChunksRoute: AppassetsAssetsAssetIdChunksRoute,
  AppassetsAssetsAssetIdEditRoute: AppassetsAssetsAssetIdEditRoute,
  AppblocksBlocksBlockIdEditRoute: AppblocksBlocksBlockIdEditRoute,
  AppbotsBotsBotIdEditRoute: AppbotsBotsBotIdEditRoute,
  AppcoursesCoursesCourseIdEditRoute: AppcoursesCoursesCourseIdEditRoute,
  ApporgsOrgsOrgIdEditRoute: ApporgsOrgsOrgIdEditRoute,
  AppusersUsersUserIdEditRoute: AppusersUsersUserIdEditRoute,
  ApporgsOrgsOrgIdProvidersProviderSlugRoute:
    ApporgsOrgsOrgIdProvidersProviderSlugRoute,
  ApporgsOrgsOrgIdProvidersAddRoute: ApporgsOrgsOrgIdProvidersAddRoute,
  ApporgsOrgsOrgIdProvidersIndexRoute: ApporgsOrgsOrgIdProvidersIndexRoute,
  ApporgsOrgsOrgIdProvidersProviderSlugEditRoute:
    ApporgsOrgsOrgIdProvidersProviderSlugEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiDocSplatServerRoute: ApiDocSplatServerRoute,
  ApiRpcSplatServerRoute: ApiRpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
